### ISSUE TITLE
Argument for @NotNull parameter 'copyPsi' of com/intellij/psi/impl/file/PsiDirectoryImpl.updateAddedFile must not be null

### ISSUE THREAD

**Issue by cassiuscai** [hsz/idea-gitignore#128]
```
Argument for @NotNull parameter 'copyPsi' of com/intellij/psi/impl/file/PsiDirectoryImpl.updateAddedFile must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'copyPsi' of com/intellij/psi/impl/file/PsiDirectoryImpl.updateAddedFile must not be null
    at com.intellij.psi.impl.file.PsiDirectoryImpl.a(PsiDirectoryImpl.java)
    at com.intellij.psi.impl.file.PsiDirectoryImpl.add(PsiDirectoryImpl.java:456)
    at com.intellij.psi.impl.file.PsiJavaDirectoryImpl.add(PsiJavaDirectoryImpl.java:64)
    at mobi.hsz.idea.gitignore.file.IgnoreTemplatesFactory.createFromTemplate(IgnoreTemplatesFactory.java:84)
    at mobi.hsz.idea.gitignore.command.CreateFileCommandAction.run(CreateFileCommandAction.java:70)
    at com.intellij.openapi.application.RunResult.run(RunResult.java:38)
    at com.intellij.openapi.command.WriteCommandAction$2$1.run(WriteCommandAction.java:114)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:931)
    at com.intellij.openapi.command.WriteCommandAction$2.run(WriteCommandAction.java:111)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:124)
    at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:99)
    at com.intellij.openapi.command.WriteCommandAction.performWriteCommandAction(WriteCommandAction.java:108)
    at com.intellij.openapi.command.WriteCommandAction.execute(WriteCommandAction.java:80)
    at mobi.hsz.idea.gitignore.daemon.MissingGitignoreNotificationProvider$1.run(MissingGitignoreNotificationProvider.java:139)
    at com.intellij.ui.EditorNotificationPanel$2.hyperlinkActivated(EditorNotificationPanel.java:93)
    at com.intellij.ui.HyperlinkAdapter.hyperlinkUpdate(HyperlinkAdapter.java:28)
    at com.intellij.ui.HyperlinkLabel.fireHyperlinkEvent(HyperlinkLabel.java:188)
    at com.intellij.ui.HyperlinkLabel.processMouseEvent(HyperlinkLabel.java:121)
    at java.awt.Component.processEvent(Component.java:6290)
    at java.awt.Container.processEvent(Container.java:2234)
    at java.awt.Component.dispatchEventImpl(Component.java:4881)
    at java.awt.Container.dispatchEventImpl(Container.java:2292)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
    at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4530)
    at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
    at java.awt.Container.dispatchEventImpl(Container.java:2278)
    at java.awt.Window.dispatchEventImpl(Window.java:2739)
    at java.awt.Component.dispatchEvent(Component.java:4703)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:751)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:702)
    at java.awt.EventQueue$3.run(EventQueue.java:696)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
    at java.awt.EventQueue$4.run(EventQueue.java:724)
    at java.awt.EventQueue$4.run(EventQueue.java:722)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:565)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by cassiuscai** [comment]
error occors when i add a .gitignore file . Intellij IDEA 14.1.3

**Comment by hsz** [comment]
@cassiuscai Thank you for reporting.

Unfortunately I cannot reproduce this issue. Can you provide more information ?
That is the specific scenario of this bug ? How does the files tree looks like ?

**Comment by cassiuscai** [comment]
- 1. create a project ,add some file, enable git in vcs menu
- 2. open a file, IDEA will prompt add a .gitignore file
![1](https://cloud.githubusercontent.com/assets/2277724/8271052/0f667810-1835-11e5-971c-b948754f1e3a.jpg)
- 3. Click the link,and the error comes up
![2](https://cloud.githubusercontent.com/assets/2277724/8271054/1b891260-1835-11e5-9572-919cf7ae32a0.jpg)
![3](https://cloud.githubusercontent.com/assets/2277724/8271061/55660114-1835-11e5-9bbe-426d4f41b331.jpg)

**Comment by hsz** [comment]
@cassiuscai Thank you for the nice explanation. 
I've followed your instructions with the various IntelliJ instances (incl. 14.1.3) and there was no error.

Can you confirm that this issue still appears with the newest plugin version `v1.1.4` ?

**Comment by hsz** [comment]
@cassiuscai Bump.

**Comment by hsz** [comment]
@cassiuscai Can you verify it with the latest `v1.3.3` ?

**Comment by cassiuscai** [comment]
Fixed with .ignore v1.3.3 and IntelliJ 2016.01

**Comment by cassiuscai** [comment]
to reproduce this issue,you should setting file types ignore .*, other wise it looks like all right

**Comment by cassiuscai** [comment]
<img width="1354" alt="screen shot 2016-05-10 at 16 05 13" src="https://cloud.githubusercontent.com/assets/2277724/15139586/84265024-16c9-11e6-907c-b5dc83a27f31.png">

Files -> Setting -> File Types -> Ignore files and folders
