### ISSUE TITLE
Exception when I tried to enable Git VCS

### ISSUE THREAD

**Issue by ndjordjevic** [hsz/idea-gitignore#134]
8:40:17 PM Created Git repository in /Users/ndjordjevic/JS/my-meanjs-app2
8:40:18 PM Throwable
           Access is allowed from event dispatch thread only.
           Details: EventQueue.isDispatchThread()=false
           isDispatchThread()=false
           Toolkit.getEventQueue()=com.intellij.ide.IdeEventQueue@66d7d18e
           Current thread: Thread[ApplicationImpl pooled thread 10,4,main] 1240624419
           SystemEventQueueThread: Thread[AWT-EventQueue-0 10.0.3#WS-141.1237, eap:false,6,main] 795188294
           "AWT-EventQueue-0 10.0.3#WS-141.1237, eap:false" prio=0 tid=0x0 nid=0x0 runnable
           java.lang.Thread.State: RUNNABLE
           at sun.lwawt.macosx.CCursorManager.nativeGetCursorPosition(Native Method)
           at sun.lwawt.macosx.CCursorManager.getCursorPosition(CCursorManager.java:54)
           at sun.lwawt.LWCursorManager.updateCursorImpl(LWCursorManager.java:80)
           at sun.lwawt.LWCursorManager.updateCursor(LWCursorManager.java:57)
           at sun.lwawt.LWComponentPeer.updateCursorImmediately(LWComponentPeer.java:896)
           at java.awt.Component.updateCursorImmediately(Component.java:3137)
           at java.awt.Container.validate(Container.java:1640)
           at javax.swing.CellRendererPa... (show balloon)

**Comment by hsz** [comment]
Thank you for reporting, this issue has been already reported with #122
