### ISSUE TITLE
Updated to 1.1.3 and got java.lang.NoSuchMethodError, IDEA 14.1.3 - build #UI-141.1010

### ISSUE THREAD

**Issue by guidomedina** [hsz/idea-gitignore#140]
Stack trace:
```
com.intellij.util.containers.ContainerUtil.isEmpty(Ljava/util/List;)Z
java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.isEmpty(Ljava/util/List;)Z
	at mobi.hsz.idea.gitignore.IgnoreManager$5$1.run(IgnoreManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

**Comment by hsz** [comment]
@guidomedina What version of IDE do you have ?

**Comment by istocniks** [comment]
same thing, IDEA 14.1.3

**Comment by guidomedina** [comment]
IDEA 14.1.3 Ultimate, Build #UI-141.1010

**Comment by hsz** [comment]
That's weird because `isEmpty(Collection<T> collection)` should accept `List` too.

https://github.com/JetBrains/intellij-community/blob/master/platform/util/src/com/intellij/util/containers/ContainerUtil.java#L2576

Anyway..

**Comment by hsz** [comment]
@guidomedina  @istocniks Thank you for the quick reaction. I've dropped last release and pushed  `v1.1.4` just right now.

**Comment by guidomedina** [comment]
No problem, I was watching TV with laptop and got notification of update so I just went ahead, then boom, thought it was more important doing a community than stupid TV ;-)
