### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by Janmm14** [hsz/idea-gitignore#144]
Stacktrace:
```
java.lang.RuntimeException: java.lang.IndexOutOfBoundsException
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.handleError(FSRecords.java:500)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords$DbConnection.access$000(FSRecords.java:138)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getParent(FSRecords.java:988)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.getParent(PersistentFSImpl.java:305)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileById(PersistentFSImpl.java:976)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.findFileByIdIfCached(PersistentFSImpl.java:957)
	at com.intellij.util.indexing.IndexInfrastructure.findFileByIdIfCached(IndexInfrastructure.java:127)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:977)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:947)
	at com.intellij.util.indexing.FileBasedIndexImpl.processExceptions(FileBasedIndexImpl.java:920)
	at com.intellij.util.indexing.FileBasedIndexImpl.processValuesImpl(FileBasedIndexImpl.java:993)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:877)
	at com.intellij.psi.search.FileTypeIndex.getFiles(FileTypeIndex.java:44)
	at mobi.hsz.idea.gitignore.IgnoreManager$5.run(IgnoreManager.java:389)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.IndexOutOfBoundsException
	at java.nio.Buffer.checkIndex(Buffer.java:546)
	at java.nio.DirectByteBuffer.getInt(DirectByteBuffer.java:681)
	at com.intellij.util.io.PagedFileStorage.getInt(PagedFileStorage.java:154)
	at com.intellij.util.io.ResizeableMappedFile.getInt(ResizeableMappedFile.java:180)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getRecordInt(FSRecords.java:1191)
	at com.intellij.openapi.vfs.newvfs.persistent.FSRecords.getParent(FSRecords.java:975)
	... 31 more
```

**Comment by hsz** [comment]
@Janmm14 Thank you for reporting.

What version of plugin and IDE do you use ?

**Comment by Janmm14** [comment]
@hsz Here you are:
Intellij: 14.1.3 CE, .ignore: 1.1.4
