### ISSUE TITLE
IllegalArgumentException when moving a project

### ISSUE THREAD

**Issue by loloakira** [hsz/idea-gitignore#145]
I moved a project from a folder to another using the move option in PyCharm (Right clic on project's name -> Refactor -> Move) resulting in that error : 

```
Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.isUnder must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.isUnder must not be null
	at mobi.hsz.idea.gitignore.util.Utils.isUnder(Utils.java)
	at mobi.hsz.idea.gitignore.util.Utils.isInProject(Utils.java:359)
	at mobi.hsz.idea.gitignore.reference.IgnoreReferenceSet$IgnoreReference.innerResolveInContext(IgnoreReferenceSet.java:191)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.innerResolve(FileReference.java:140)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:566)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:560)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:188)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.multiResolve(FileReference.java:128)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.resolve(FileReference.java:332)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.resolve(FileReference.java:52)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:330)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:201)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:429)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:426)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:402)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:202)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

Therefore, it seems that the exceptions disapears after rebooting the IDE.

**Comment by hsz** [comment]
@loloakira Thank you for reporting.

What version of plugin do you use ?

**Comment by loloakira** [comment]
Sorry for not having specified that. I use the 1.1.4
