### ISSUE TITLE
NullPointerException when creating a new project

### ISSUE THREAD

**Issue by christopher-hopper** [hsz/idea-gitignore#151]
### Issue

When creating a new project from existing sources in PhpStorm 8.0.3 build 139.1348, with .ignore plug-in version 1.1.2, I received a `NullPointerException: null` error message from the .ignore plug-in.

### Steps to reproduce

1. Open PhpStorm
1. Close all open projects
1. Create a new project from existing sources
1. Select Existing files, web server not yet configured
1. Choose the Project Root folder for the project with an existing `.gitignore` file in it

### Debug output

```
null
java.lang.NullPointerException
  at mobi.hsz.idea.gitignore.util.Utils$2.compare(Utils.java:436)
  at mobi.hsz.idea.gitignore.util.Utils$2.compare(Utils.java:433)
  at com.intellij.util.containers.ContainerUtil.sort(ContainerUtil.java:1513)
  at mobi.hsz.idea.gitignore.util.Utils.ignoreFilesSort(Utils.java:433)
  at mobi.hsz.idea.gitignore.IgnoreManager$5.run(IgnoreManager.java:365)
  at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
  at com.intellij.util.Alarm$Request$1.run(Alarm.java:351)
  at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:318)
  at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:312)
  at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:745)
  at java.awt.EventQueue.access$300(EventQueue.java:103)
  at java.awt.EventQueue$3.run(EventQueue.java:706)
  at java.awt.EventQueue$3.run(EventQueue.java:704)
  at java.security.AccessController.doPrivileged(Native Method)
  at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:76)
  at java.awt.EventQueue.dispatchEvent(EventQueue.java:715)
  at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:748)
  at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:577)
  at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:384)
  at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:242)
  at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:161)
  at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:150)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:146)
  at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:138)
  at java.awt.EventDispatchThread.run(EventDispatchThread.java:91)
```

**Comment by hsz** [comment]
@christopher-hopper Thank you for reporting.
Does this error also appears in version `v.1.1.4` ?

**Comment by christopher-hopper** [comment]
So, I upgraded to PhpStorm 9.0 and your plugin .ignore v.1.1.4, after which the above issue seemed to be sorted. 

I still have PhpStorm 8.0.3, so before you close this, let me just check if the issue is fixed there too by plugin v.1.1.4.

**Comment by hsz** [comment]
@christopher-hopper What is the feedback ? Can we close this issue ?

**Comment by christopher-hopper** [comment]
@hsz Sorry for the delay, I was distracted and lost track of this. I tested again following the **steps to reproduce** above with the following software combination: 

| software | version |
|---|---|
| PhpStorm | 8.0.3 build 139.1348 |
| .ignore | 1.1.4 |

_The plugin no longer caused any errors or issues as described._

Apologies for the report as it was against your older version of the plugin. I do wonder though if I can have PhpStorm check for plugin updates in the same way it checks for software updates from JetBrains. I'll look around and ask JetBrains if I cannot find anything. 

Seems odd that this wouldn't be a feature. PhpStorm clearly checks plugins for updates when doing a major version upgrade.

**Comment by hsz** [comment]
Thank you for the summary. I'll mark this issue as invalid just for the automatic changelog generator. 

Good luck!
