### ISSUE TITLE
Renaming project directory causes IllegalArgumentException

### ISSUE THREAD

**Issue by riggs** [hsz/idea-gitignore#168]
Renaming the project directory via Refactor -> Rename: Rename Directory menu (in WebStorm) causes this issue.
```
Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
    at mobi.hsz.idea.gitignore.util.Utils.getRelativePath(Utils.java)
    at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:192)
    at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:262)
    at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:68)
    at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.calcStatus(FileStatusManagerImpl.java:143)
    at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.getStatus(FileStatusManagerImpl.java:278)
    at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.b(LineStatusTrackerManager.java:266)
    at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:235)
    at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:229)
    at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:206)
    at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.access$1600(LineStatusTrackerManager.java:68)
    at com.intellij.openapi.vcs.impl.LineStatusTrackerManager$MyFileStatusListener.fileStatusesChanged(LineStatusTrackerManager.java:386)
    at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.fileStatusesChanged(FileStatusManagerImpl.java:219)
    at com.intellij.openapi.vcs.impl.FileStatusManagerImpl$6.run(FileStatusManagerImpl.java:209)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    <snip>

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
    at mobi.hsz.idea.gitignore.util.Utils.getRelativePath(Utils.java)
    at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:192)
    at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:262)
    at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:68)
    at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.calcStatus(FileStatusManagerImpl.java:143)
    at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.getStatus(FileStatusManagerImpl.java:278)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getFileColor(FileEditorManagerImpl.java:343)
    at com.intellij.openapi.fileEditor.impl.EditorsSplitters.updateFileColor(EditorsSplitters.java:399)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.a(FileEditorManagerImpl.java:374)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$2500(FileEditorManagerImpl.java:102)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyFileStatusListener.a(FileEditorManagerImpl.java:1830)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyFileStatusListener.access$2400(FileEditorManagerImpl.java:1800)
    at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyFileStatusListener$1.run(FileEditorManagerImpl.java:1815)
    at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    <snip>
```

**Comment by hsz** [comment]
@riggs Thank you for your report. This issue has been fixed with #170 

Fix will be available in release `v1.3`.
