### ISSUE TITLE
Exception thrown when project root directory is renamed

### ISSUE THREAD

**Issue by bavellone** [hsz/idea-gitignore#170]
I renamed the project root directory and received the following error message:
```
Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
```
Here are the error details :
```
Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
	at mobi.hsz.idea.gitignore.util.Utils.getRelativePath(Utils.java)
	at mobi.hsz.idea.gitignore.IgnoreManager$5$1.run(IgnoreManager.java:463)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:152)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:137)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:400)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:56)
```

I'm running 64-bit Arch linux, Webstorm v10.0.4

**Comment by hsz** [comment]
@bavellone Thank you for reporting.
Fix will be available in release `v1.3`.
