### ISSUE TITLE
PersistentFS returned duplicate file names(Webcover.jpg,webcover.jpg)

### ISSUE THREAD

**Issue by jacobsenj** [hsz/idea-gitignore#172]
PersistentFS returned duplicate file names(Webcover.jpg,webcover.jpg) ignoreCase: true SystemInfo.isFileSystemCaseSensitive: false SystemInfo.OS: Mac OS X 10.11.1 wasChildrenLoaded: true in the dir: ....

The given dir is a symlink to a linux file server mount.

**Comment by DIOHz0r** [comment]
Same problem here, more info of the problem...

PersistentFS returned duplicate file names(imagen1.jpg,Imagen1.jpg) ignoreCase: true SystemInfo.isFileSystemCaseSensitive: false SystemInfo.OS: Windows 7 6.1 wasChildrenLoaded: false in the dir: file://Z:/www.celulas.local/web/modules/Carousel/images/img_carr; children: [Imagen1.jpg (10322), imagen2.jpg (10323), imagen1.jpg (10324)]
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:115)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl$2.compare(VirtualDirectoryImpl.java:311)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl$2.compare(VirtualDirectoryImpl.java:304)
	at java.util.TimSort.binarySort(TimSort.java:292)
	at java.util.TimSort.sort(TimSort.java:217)
	at java.util.Arrays.sort(Arrays.java:1438)
	at com.intellij.openapi.vfs.newvfs.impl.VirtualDirectoryImpl.getChildren(VirtualDirectoryImpl.java:304)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:278)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:299)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:299)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:299)
	at com.intellij.openapi.vfs.VfsUtilCore.visitChildrenRecursively(VfsUtilCore.java:299)
	at com.intellij.openapi.vfs.VfsUtilCore.iterateChildrenRecursively(VfsUtilCore.java:247)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.iterateContent(ProjectFileIndexImpl.java:66)
	at com.intellij.util.indexing.FileBasedIndexImpl$24.run(FileBasedIndexImpl.java:2578)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2562)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1112)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:987)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:964)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:937)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1010)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:894)
	at com.intellij.psi.search.FileTypeIndex.getFiles(FileTypeIndex.java:44)
	at mobi.hsz.idea.gitignore.IgnoreManager$5.run(IgnoreManager.java:391)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.f(IdeEventQueue.java:861)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:380)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by hsz** [comment]
@jacobsenj  @DIOHz0r Thank you for reporting.

This issue is well known in the JetBrains bugtracker: https://youtrack.jetbrains.com/issues/IDEA?q=PersistentFS+returned+duplicate+file

There is possible fix for that:

> Now I have absolutely no idea why Android Studio would be reading anything at all from this seemingly arbitrary directory at all nor why this became a problem just now, after updating to Yosemite. Somehow to explaining Android Studio that it was running on a case-sensitive volume by editing IDE_INSTALL_DIR\bin\idea.properties to include an entry idea.case.sensitive.fs=true finally did the trick.

ref: http://www.linkhal.de/blog/2014/10/fixing-startupfreezing-issues-with-intellijandroid-studio-on-yosemite-on-case-sensitive-volumes/

It is not related to the `.ignore` plugin itself, but calling a IntelliJ SDK method.


Does it cause any problems in the work process or just showing an error log ?
