### ISSUE TITLE
Crashed due to file does not exit

### ISSUE THREAD

**Issue by paraglohiya** [hsz/idea-gitignore#191]
another interesting thing is after it crashed the IDE is blinking between Bold colors and light colors :)

My mac is completely now showing bold colors
```
/Users/plohi111/Library/Caches/IntelliJIdea15/index/filetypes/filetypes.len (No such file or directory)
java.io.FileNotFoundException: /Users/plohi111/Library/Caches/IntelliJIdea15/index/filetypes/filetypes.len (No such file or directory)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at com.intellij.util.io.ResizeableMappedFile$1.execute(ResizeableMappedFile.java:133)
	at com.intellij.util.io.ResizeableMappedFile$1.execute(ResizeableMappedFile.java:128)
	at com.intellij.openapi.util.io.FileUtilRt.doIOOperation(FileUtilRt.java:740)
	at com.intellij.util.io.ResizeableMappedFile.writeLength(ResizeableMappedFile.java:128)
	at com.intellij.util.io.ResizeableMappedFile.force(ResizeableMappedFile.java:165)
	at com.intellij.util.io.PersistentEnumeratorBase.doFlush(PersistentEnumeratorBase.java:544)
	at com.intellij.util.io.PersistentBTreeEnumerator.doFlush(PersistentBTreeEnumerator.java:513)
	at com.intellij.util.io.PersistentEnumeratorBase.flush(PersistentEnumeratorBase.java:534)
	at com.intellij.util.io.PersistentEnumeratorBase.force(PersistentEnumeratorBase.java:555)
	at com.intellij.util.io.PersistentEnumeratorBase.markCorrupted(PersistentEnumeratorBase.java:600)
	at com.intellij.util.io.PersistentEnumeratorBase.doEnumerate(PersistentEnumeratorBase.java:294)
	at com.intellij.util.io.PersistentEnumeratorBase.tryEnumerate(PersistentEnumeratorBase.java:274)
	at com.intellij.util.io.PersistentEnumeratorDelegate.tryEnumerate(PersistentEnumeratorDelegate.java:87)
	at com.intellij.util.io.PersistentHashMap.doGet(PersistentHashMap.java:491)
	at com.intellij.util.io.PersistentHashMap.get(PersistentHashMap.java:464)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:118)
	at com.intellij.util.indexing.MapIndexStorage$2$1.compute(MapIndexStorage.java:106)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.a(ChangeTrackingValueContainer.java:121)
	at com.intellij.util.indexing.ChangeTrackingValueContainer.getValueIterator(ChangeTrackingValueContainer.java:82)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:989)
	at com.intellij.util.indexing.FileBasedIndexImpl$14.convert(FileBasedIndexImpl.java:964)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:937)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1010)
	at com.intellij.util.indexing.FileBasedIndexImpl.getContainingFiles(FileBasedIndexImpl.java:894)
	at com.intellij.psi.search.FileTypeIndex.getFiles(FileTypeIndex.java:44)
	at mobi.hsz.idea.gitignore.IgnoreManager$5.run(IgnoreManager.java:391)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request$1.run(Alarm.java:352)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:337)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:321)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment]
@paraglohiya Thank you for reporting this issue. It is not directly related to the `.ignore` plugin.

In fact, there is following line:

    at mobi.hsz.idea.gitignore.IgnoreManager$5.run(IgnoreManager.java:391)

which invokes IDE method:

    Collection<VirtualFile> virtualFiles = FileTypeIndex.getFiles(language.getFileType(), scope);

It may be caused because IDE lost some files (?).
The `FileNotFoundException` exception cannot be even catched in my code:

![image](https://cloud.githubusercontent.com/assets/108333/13844335/7e88500a-ec39-11e5-9f45-fb911558389c.png)
