### ISSUE TITLE
Error: String index out of range: 27

### ISSUE THREAD

**Issue by migelsabre** [hsz/idea-gitignore#205]
Windows 7 x64, PhpStorm 2016.1 (Build PS #145.258), JRE 1.8.0_65-b17 amd64
Updating plugin to v 1.3 causes sequence of errors while reindexing project files, during process PhpStorm nearly hangs for about a minute.

```
String index out of range: 27
java.lang.StringIndexOutOfBoundsException: String index out of range: 27
	at java.lang.String.charAt(String.java:658)
	at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3797)
	at java.util.regex.Pattern$Curly.match1(Pattern.java:4287)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4236)
	at java.util.regex.Pattern$Curly.match1(Pattern.java:4287)
	at java.util.regex.Pattern$Curly.match(Pattern.java:4236)
	at java.util.regex.Pattern$Begin.match(Pattern.java:3525)
	at java.util.regex.Matcher.match(Matcher.java:1270)
	at java.util.regex.Matcher.matches(Matcher.java:604)
	at mobi.hsz.idea.gitignore.util.Utils.match(Utils.java:512)
	at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:200)
	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:263)
	at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:68)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.calcStatus(FileStatusManagerImpl.java:144)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.getStatus(FileStatusManagerImpl.java:279)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.getFileStatus(AbstractPsiBasedNode.java:121)
	at com.intellij.ide.util.treeView.AbstractTreeNode.setForcedForeground(AbstractTreeNode.java:81)
	at com.intellij.ide.util.treeView.AbstractTreeNode.postprocess(AbstractTreeNode.java:77)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:91)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:937)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1838)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:933)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:885)
	at com.intellij.ide.util.treeView.AbstractTreeUi.collectNodesToInsert(AbstractTreeUi.java:2257)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4600(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$30.perform(AbstractTreeUi.java:1394)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.consume(TreeRunnable.java:45)
	at org.jetbrains.concurrency.AsyncPromise.setResult(AsyncPromise.java:314)
	at org.jetbrains.concurrency.DonePromise.notify(DonePromise.java:88)
	at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2092)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$6000(AbstractTreeUi.java:66)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37$1.perform(AbstractTreeUi.java:1984)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2187)
	at com.intellij.ide.util.treeView.AbstractTreeUi$37.perform(AbstractTreeUi.java:1979)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:34)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.c(IdeEventQueue.java:857)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:658)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:386)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment]
@migelsabre Thank you for the quick report - I'll release fix in a minutes.

**Comment by hsz** [comment]
@migelsabre Thank you for the quick report - I'll release fix in a minutes.

Can you provide me your gitignore content ?

**Comment by migelsabre** [comment]
Note, that I have some of .gitignore in nested folders.

**1st file:**
.settings
.idea
.project
*.sublime-*
.externalToolBuilders
*~
*.diff
*.patch
*.bak
*.log
*.swp
*.min.min.js
*.min.min.css
.DS_Store
composer.lock
www/data/
www/cgi-bin/
www/assets/
www/tmp/
www/framework/
www/logs/

**2nd file:**
vendor/
!vendor/packages/
us.stackdump

**3rd file:**
data/
cgi-bin/
assets/
tmp/
framework/
logs/

# phpstorm project files
.idea

# netbeans project files
nbproject

# zend studio for eclipse project files
.buildpath
.project
.settings

# windows thumbnail cache
Thumbs.db

# composer vendor dir
protected/vendor
!protected/vendor/packages

# composer itself is not needed
composer.phar
# composer.lock should not be committed as we always want the latest versions
/composer.lock

# Mac DS_Store Files
.DS_Store

# phpunit itself is not needed
phpunit.phar
# local phpunit config
/phpunit.xml

**Comment by hsz** [comment]
Thanks ! Rules looks correct - it looks like there is a problem with matching file names. I've prepared fix already.

**Comment by migelsabre** [comment]
Thank you for quick fix!
And I should refactor my ,gitignores, because some rules are excessive and overlapping.
