### ISSUE TITLE
expand project tree view very slow,IDEA 2016.1.1

### ISSUE THREAD

**Issue by jiangnanrusheng** [hsz/idea-gitignore#209]
update idea to 2016.1.1 yesterday,i found one of my project expand verfy slow,after click to expand,it takes about 3 sec.I check threaddump and found the problem.

java.lang.Thread.State: RUNNABLE
 (in native)
	at java.lang.ProcessImpl.waitForInterruptibly(Native Method)
	at java.lang.ProcessImpl.waitFor(ProcessImpl.java:449)
	at mobi.hsz.idea.gitignore.lang.kind.GitLanguage.getOuterFile(GitLanguage.java:91)
	at mobi.hsz.idea.gitignore.psi.IgnoreFile.isOuter(IgnoreFile.java:161)
	at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:180)
	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:264)
	at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:68)

when i disable .ignore plugin,everything just work fun,please fix this bug.
[threadDump-20160401-115729.txt](https://github.com/hsz/idea-gitignore/files/198967/threadDump-20160401-115729.txt)

**Comment by hsz** [comment]
@jiangnanrusheng Thanks for reporting this issue and a helpful thread dump. It has already been reported in #204 
I'll close this one - please keep an eye on the above thread, thanks !
