### ISSUE TITLE
NoSuchMethodError on latest (v1.3.2)

### ISSUE THREAD

**Issue by martixy** [hsz/idea-gitignore#211]
Once I updated, the new version successfully managed to crap all over the IDE(PhpStorm 9):

    mobi.hsz.idea.gitignore.parser.IgnoreParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;
    java.lang.NoSuchMethodError: mobi.hsz.idea.gitignore.parser.IgnoreParserUtil.enter_section_(Lcom/intellij/lang/PsiBuilder;IILcom/intellij/psi/tree/IElementType;Ljava/lang/String;)Lcom/intellij/lang/PsiBuilder$Marker;
        at mobi.hsz.idea.gitignore.parser.IgnoreParser.ENTRY_DIRECTORY(IgnoreParser.java:88)
        at mobi.hsz.idea.gitignore.parser.IgnoreParser.item_(IgnoreParser.java:211)
        at mobi.hsz.idea.gitignore.parser.IgnoreParser.gitignoreFile(IgnoreParser.java:194)
        at mobi.hsz.idea.gitignore.parser.IgnoreParser.parse_root_(IgnoreParser.java:48)
        at mobi.hsz.idea.gitignore.parser.IgnoreParser.parseLight(IgnoreParser.java:42)
        at mobi.hsz.idea.gitignore.parser.IgnoreParser.parse(IgnoreParser.java:18)
        at com.intellij.psi.tree.ILazyParseableElementType.doParseContents(ILazyParseableElementType.java:64)
        at com.intellij.psi.tree.IFileElementType.parseContents(IFileElementType.java:43)
        at com.intellij.psi.impl.source.tree.LazyParseableElement.f(LazyParseableElement.java:172)
        at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:212)
        at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:36)
        at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
        at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:769)
        at com.intellij.codeInsight.daemon.impl.Divider.a(Divider.java:95)
        at com.intellij.codeInsight.daemon.impl.Divider.divideInsideAndOutside(Divider.java:54)
        at com.intellij.codeInsight.daemon.impl.GeneralHighlightingPass.collectInformationWithProgress(GeneralHighlightingPass.java:186)
        at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:97)
        at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:67)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
        at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1098)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
        at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:452)
        at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:402)
        at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
        at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
        at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask.exec(JobLauncherImpl.java:189)
        at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
        at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
        at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
        at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)

On a semi-related note, I couldn't even successfully downgrade to v1.2, resulting in an `Unable to save plugin settings` error.

**Comment by hsz** [comment]
@martixy Thanks for reporting. I've fixed it and it will be available in the next release (v1.3.3)

**Comment by martixy** [comment]
Thanks, can confirm it's fine now.
