### ISSUE TITLE
Fatal Error in PhpStorm 2016.1.1

### ISSUE THREAD

**Issue by PastisD** [hsz/idea-gitignore#223]
```
com.intellij.psi.impl.source.html.HtmlFileImpl cannot be cast to mobi.hsz.idea.gitignore.psi.IgnoreFile
java.lang.ClassCastException: com.intellij.psi.impl.source.html.HtmlFileImpl cannot be cast to mobi.hsz.idea.gitignore.psi.IgnoreFile
	at mobi.hsz.idea.gitignore.reference.IgnoreReferenceSet$IgnoreReference.innerResolveInContext(IgnoreReferenceSet.java:199)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.innerResolve(FileReference.java:145)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:575)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:569)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:193)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.multiResolve(FileReference.java:133)
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreUnusedEntryInspection$1.visitEntry(IgnoreUnusedEntryInspection.java:79)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryFile(IgnoreVisitor.java:19)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryFileImpl.accept(IgnoreEntryFileImpl.java:20)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:709)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$1200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$6.process(LocalInspectionsPass.java:357)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$6.process(LocalInspectionsPass.java:354)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)

```

**Comment by tansautn** [comment]
please write down exactly build version , then if got error when install by GUI in phpStorm > download and install from disk : https://plugins.jetbrains.com/plugin/7495

**Comment by PastisD** [comment]
There are no errors on installation. The plugin seems to work fine.
Just sometimes this exception appears. I don't know what causes the exception.

```
PhpStorm 2016.1.1
Build #PS-145.969, built on April 22, 2016
JRE: 1.8.0_77-b03 x86
JVM: Java HotSpot(TM) Server VM by Oracle Corporation
```

**Comment by hsz** [comment]
Thanks, but it has been already reported and fixed with #220

**Comment by PastisD** [comment]
Sorry, I didn't check in closed PR...

**Comment by hsz** [comment]
@PastisD no problem -  it's always better to have more reports. 👌
