### ISSUE TITLE
NoSuchMethodError in IDEA 2016.2 EAP

### ISSUE THREAD

**Issue by ohlle** [hsz/idea-gitignore#225]
I'm getting the following stacktrace in IDEA 2016.2 EAP.
```
com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/Collection;
java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/Collection;
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreCoverEntryInspection$2.visitEntry(IgnoreCoverEntryInspection.java:153)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryFile(IgnoreVisitor.java:19)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryFileImpl.accept(IgnoreEntryFileImpl.java:20)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:200)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:822)
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreCoverEntryInspection.checkFile(IgnoreCoverEntryInspection.java:144)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at mobi.hsz.idea.gitignore.psi.IgnoreFile.accept(IgnoreFile.java:120)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:123)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:212)
	at com.intellij.concurrency.ApplierCompleter.c(ApplierCompleter.java:141)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1063)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:96)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:472)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:421)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.b(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:91)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

**Comment by hsz** [comment]
@ohlle Thank you for reporting this issue. What exacly IDE build and plugin version do you have ?

I've tried to reproduce it on build IC-162.74.16 without any problems.

> IntelliJ IDEA (Community Edition) 2016.2 EAP
> Build #IC-162.74.16, built on May 13, 2016
> JRE: 1.8.0_92-b14 amd64
> JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by ohlle** [comment]
@hsz 
IntelliJ IDEA 2016.2 EAP
Build #IU-162.74.16, built on May 13, 2016
JRE: 1.8.0_76-release-b66 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

.ignore
Version: 1.3.3

**Comment by bountin** [comment]
Same issue on a mac with a simple .dockerignore (see below)
```
IntelliJ IDEA 2016.2 EAP
Build #IU-162.74.16, built on May 13, 2016
IntelliJ IDEA EAP User
Expiration date: June 12, 2016
JRE: 1.8.0_76-release-b185 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
```
node_modules
config.json
database.json
```

**Comment by ohlle** [comment]
Oh, I forgot to mention. I'm using Ubuntu 16.04.

**Comment by hsz** [comment]
@ohlle @bountin Can you confirm that attached build fixes the problem ?
[idea-gitignore-1.3.3.zip](https://github.com/hsz/idea-gitignore/files/271423/idea-gitignore-1.3.3.zip)

**Comment by hsz** [comment]
@oliviersalzburg @sheltonn @ohlle @bountin 
Can you confirm that attached build fixes the problem ?
[idea-gitignore-1.3.3.zip](https://github.com/hsz/idea-gitignore/files/271423/idea-gitignore-1.3.3.zip)

**Comment by hsz** [comment]
@oliversalzburg @sheltonn @ohlle @bountin 
Can you confirm that attached build fixes the problem ?
[idea-gitignore-1.3.3.zip](https://github.com/hsz/idea-gitignore/files/271423/idea-gitignore-1.3.3.zip)

**Comment by oliversalzburg** [comment]
@hsz Looks good

**Comment by ohlle** [comment]
@hsz I'm unable to reproduce the error with the new version of the plugin. Thanks!
