### ISSUE TITLE
com.intellij.psi.impl.source.xml.XmlFileImpl cannot be cast to mobi.hsz.idea.gitignore.psi.IgnoreFile

### ISSUE THREAD

**Issue by gosuvigi** [hsz/idea-gitignore#226]
I get this error a lot of times, I don't know how it started but I noticed it after I inserted a bogus  language/reference (I think it was bazaar) via the intent actions into an XML file, maybe this is what triggered it.
```
com.intellij.psi.impl.source.xml.XmlFileImpl cannot be cast to mobi.hsz.idea.gitignore.psi.IgnoreFile
java.lang.ClassCastException: com.intellij.psi.impl.source.xml.XmlFileImpl cannot be cast to mobi.hsz.idea.gitignore.psi.IgnoreFile
	at mobi.hsz.idea.gitignore.reference.IgnoreReferenceSet$IgnoreReference.innerResolveInContext(IgnoreReferenceSet.java:199)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.innerResolve(FileReference.java:145)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:575)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference$MyResolver.resolve(FileReference.java:569)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:193)
	at com.intellij.psi.impl.source.resolve.reference.impl.providers.FileReference.multiResolve(FileReference.java:133)
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreUnusedEntryInspection$1.visitEntry(IgnoreUnusedEntryInspection.java:79)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryFile(IgnoreVisitor.java:19)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryFileImpl.accept(IgnoreEntryFileImpl.java:20)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:709)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$1200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$6.process(LocalInspectionsPass.java:357)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$6.process(LocalInspectionsPass.java:354)
	at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:148)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.JobLauncherImpl$2.run(JobLauncherImpl.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.JobLauncherImpl.a(JobLauncherImpl.java:158)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:96)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:57)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspectInjectedPsi(LocalInspectionsPass.java:361)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:266)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:233)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:141)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:444)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:435)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:432)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:408)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:206)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by hsz** [comment]
@gosuvigi Thank you for creating the issue - it was already reported in #223 and fixed. It'll be available in the next release.
