### ISSUE TITLE
NoSuchMethodError: in version 1.4

### ISSUE THREAD

**Issue by hailwood** [hsz/idea-gitignore#227]
This error occurs every time the editor is modified for the .gitignore file. (e.g. clicking somewhere).

````
NoSuchMethodError: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/List;
````

PHPstorm 2016.1.1

**Comment by skrodal** [comment]
Same version and same error as @hailwood

**Comment by cikichen** [comment]
+1
windows7 + as 2.1.1

```
com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/List;
java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/List;
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreCoverEntryInspection$2.visitEntry(IgnoreCoverEntryInspection.java:153)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryFile(IgnoreVisitor.java:19)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryFileImpl.accept(IgnoreEntryFileImpl.java:20)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:199)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:794)
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreCoverEntryInspection.checkFile(IgnoreCoverEntryInspection.java:144)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at mobi.hsz.idea.gitignore.psi.IgnoreFile.accept(IgnoreFile.java:121)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:320)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$4.process(LocalInspectionsPass.java:315)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1180)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by hsz** [comment]
Thanks for the quick issue report !
I have no idea, what JetBrains have done with this method, but the API didn't changed. ;-) I've cloned this `intersection` method to my project, so it shouldn't appear again anymore.

Please update to `v1.4.1`

**Comment by hsz** [comment]
@hailwood @skrodal @cikichen 

Thanks for the quick issue report !
I have no idea, what JetBrains have done with this method, but the API didn't changed. ;-) I've cloned this `intersection` method to my project, so it shouldn't appear again anymore.

Please update to `v1.4.1`

**Comment by skrodal** [comment]
Thanks @hsz - 1.4.1 fixed it for me 👍

**Comment by cikichen** [comment]
@hsz Thanks.Fixed!

**Comment by hailwood** [comment]
That response time though - A class! :+1:
