### ISSUE TITLE
NoSuchMethodError on ContainerUtil.intersection

### ISSUE THREAD

**Issue by SamuelMarks** [hsz/idea-gitignore#231]
WebStorm 2016 1.2 with Oracle JVM 1.8.0_91 on Ubuntu 16.04 x64:
```
com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/List;
java.lang.NoSuchMethodError: com.intellij.util.containers.ContainerUtil.intersection(Ljava/util/Collection;Ljava/util/Collection;)Ljava/util/List;
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreCoverEntryInspection$2.visitEntry(IgnoreCoverEntryInspection.java:153)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryFile(IgnoreVisitor.java:19)
	at mobi.hsz.idea.gitignore.psi.IgnoreVisitor.visitEntryDirectory(IgnoreVisitor.java:15)
	at mobi.hsz.idea.gitignore.psi.impl.IgnoreEntryDirectoryImpl.accept(IgnoreEntryDirectoryImpl.java:20)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.acceptChildren(SharedImplUtil.java:199)
	at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:820)
	at mobi.hsz.idea.gitignore.codeInspection.IgnoreCoverEntryInspection.checkFile(IgnoreCoverEntryInspection.java:144)
	at com.intellij.codeInspection.LocalInspectionTool$1.visitFile(LocalInspectionTool.java:156)
	at mobi.hsz.idea.gitignore.psi.IgnoreFile.accept(IgnoreFile.java:121)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:81)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:294)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$200(LocalInspectionsPass.java:73)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:261)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:256)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:128)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1178)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:443)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.concurrency.ApplierCompleter.a(ApplierCompleter.java:112)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:88)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:108)
```

**Comment by hsz** [comment]
@SamuelMarks  did you updated plugin to v1. 4.1?

**Comment by SamuelMarks** [comment]
Oh, usually I get a message telling me to upgrade. Looks like you must've fixed it, cheers.
