### ISSUE TITLE
Repeated IllegalStateExceptions in PhpStorm 2016.2.1

### ISSUE THREAD

**Issue by tdukart** [hsz/idea-gitignore#252]
I'm getting this error repeatedly (~35 times in the past 10 minutes) in my PhpStorm Event Log.

```
update failed for AnAction with ID=Vcs.ShowTabbedFileHistory: @NotNull method mobi/hsz/idea/gitignore/outer/OuterIgnoreLoaderComponent.getOuterFiles must not return null
java.lang.IllegalStateException: @NotNull method mobi/hsz/idea/gitignore/outer/OuterIgnoreLoaderComponent.getOuterFiles must not return null
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreLoaderComponent.getOuterFiles(OuterIgnoreLoaderComponent.java:124)
	at mobi.hsz.idea.gitignore.lang.IgnoreLanguage.getOuterFiles(IgnoreLanguage.java:206)
	at mobi.hsz.idea.gitignore.psi.IgnoreFile.isOuter(IgnoreFile.java:154)
	at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:182)
	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:315)
	at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:69)
```

(clipped... see full trace at https://gist.github.com/tdukart/f4a1056ebe2df4640ae8ebe37b087ee2)

I'm running PhpStorm 2016.2.1 on OS X 10.11.6.

**Comment by hsz** [comment]
@tdukart Thank you for reporting this issue. It has been reported and fixed with #240
