### ISSUE TITLE
NegativeArraySizeException when opening .md.erb file

### ISSUE THREAD

**Issue by vsch** [hsz/idea-gitignore#259]
The plugin causes an exception when opening the [following file](https://github.com/interagent/prmd/blob/master/lib/prmd/templates/schemata.md.erb) in IDEA with Ruby plugin or RubyMine.

It appears to be an IDE bug not related to the plugin because it was reported in my [Markdown Navigator](https://github.com/vsch/idea-multimarkdown/issues/307) plugin. Once I wrapped the API call in try/catch to ignore the exception, .ignore plugin started to cause the same exception.

I opened an issue: https://youtrack.jetbrains.com/issue/RUBY-18589 but until it is fixed you can avoid the bug by wrapping the call in ` try { } catch (Throwable ignored) {}`

Stack trace:

```
Error executing task mobi.hsz.idea.gitignore.IgnoreManager$5$1$1@b398aff
java.lang.NegativeArraySizeException
	at com.intellij.psi.impl.source.CharTableImpl.b(CharTableImpl.java:87)
	at com.intellij.psi.impl.source.CharTableImpl.access$600(CharTableImpl.java:35)
	at com.intellij.psi.impl.source.CharTableImpl$StringHashToCharSequencesMap.b(CharTableImpl.java:274)
	at com.intellij.psi.impl.source.CharTableImpl$StringHashToCharSequencesMap.access$200(CharTableImpl.java:217)
	at com.intellij.psi.impl.source.CharTableImpl.a(CharTableImpl.java:57)
	at com.intellij.psi.impl.source.CharTableImpl.intern(CharTableImpl.java:72)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.createOuterLanguageElement(TemplateDataElementType.java:202)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.a(TemplateDataElementType.java:174)
	at com.intellij.psi.templateLanguages.TemplateDataElementType.parseContents(TemplateDataElementType.java:93)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.b(LazyParseableElement.java:192)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:240)
	at com.intellij.psi.impl.source.tree.LazyParseableElement.getFirstChildNode(LazyParseableElement.java:39)
	at com.intellij.psi.impl.source.tree.SharedImplUtil.getFirstChild(SharedImplUtil.java:52)
	at com.intellij.psi.impl.source.PsiFileImpl.getFirstChild(PsiFileImpl.java:835)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:515)
	at com.intellij.psi.SingleRootFileViewProvider.findElementAt(SingleRootFileViewProvider.java:472)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.b(BreadcrumbsXmlWrapper.java:323)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:295)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:268)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:351)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.a(BreadcrumbsXmlWrapper.java:213)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper.access$000(BreadcrumbsXmlWrapper.java:75)
	at com.intellij.xml.breadcrumbs.BreadcrumbsXmlWrapper$1.fileStatusesChanged(BreadcrumbsXmlWrapper.java:103)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.fileStatusesChanged(FileStatusManagerImpl.java:217)
	at mobi.hsz.idea.gitignore.IgnoreManager$5$1$1.run(IgnoreManager.java:504)
	at com.intellij.openapi.project.DumbServiceImpl.b(DumbServiceImpl.java:327)
	at com.intellij.openapi.project.DumbPermissionServiceImpl.allowStartingDumbModeInside(DumbPermissionServiceImpl.java:37)
	at com.intellij.openapi.project.DumbService.allowStartingDumbModeInside(DumbService.java:283)
	at com.intellij.openapi.project.DumbServiceImpl.d(DumbServiceImpl.java:306)
	at com.intellij.openapi.project.DumbServiceImpl.e(DumbServiceImpl.java:288)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:82)
	at com.intellij.openapi.project.DumbServiceImpl.a(DumbServiceImpl.java:288)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.access$300(TransactionGuardImpl.java:40)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:73)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:326)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:310)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.i(IdeEventQueue.java:829)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:665)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:385)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by vsch** [comment]
No need, the issue was caused by templated languages and my plugin lexer not playing together.
