### ISSUE TITLE
ClassNotFoundException: mobi.hsz.idea.gitignore.FilesIndexCacheProjectComponent

### ISSUE THREAD

**Issue by igreenfield** [hsz/idea-gitignore#297]
```
2017-02-08 13:11:25,272 [  12075]   INFO - roject.impl.ProjectManagerImpl - com.intellij.diagnostic.PluginException: mobi.hsz.idea.gitignore.FilesIndexCacheProjectComponent PluginClassLoader[mobi.hsz.idea.gitignore, 1.6] [Plugin: mobi.hsz.idea.gitignore] 
com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException: mobi.hsz.idea.gitignore.FilesIndexCacheProjectComponent PluginClassLoader[mobi.hsz.idea.gitignore, 1.6] [Plugin: mobi.hsz.idea.gitignore]
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:249)
	at com.intellij.openapi.components.impl.PlatformComponentManagerImpl.handleInitComponentError(PlatformComponentManagerImpl.java:43)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:411)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:287)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:222)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.d(ProjectManagerImpl.java:459)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.access$100(ProjectManagerImpl.java:60)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:406)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.compute(ProjectManagerImpl.java:403)
	at com.intellij.openapi.progress.Task$WithResult.run(Task.java:307)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:710)
	at com.intellij.openapi.progress.impl.CoreProgressManager$11.run(CoreProgressManager.java:423)
	at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:572)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:309)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.intellij.diagnostic.PluginException: mobi.hsz.idea.gitignore.FilesIndexCacheProjectComponent PluginClassLoader[mobi.hsz.idea.gitignore, 1.6] [Plugin: mobi.hsz.idea.gitignore]
	... 26 more
Caused by: java.lang.ClassNotFoundException: mobi.hsz.idea.gitignore.FilesIndexCacheProjectComponent PluginClassLoader[mobi.hsz.idea.gitignore, 1.6]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:64)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:392)
	... 23 more
```

**Comment by hsz** [comment]
@igreenfield Thank you for the report. What _latest intellij_ means ? Can you provide me exact version?

**Comment by igreenfield** [comment]
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation

**Comment by hsz** [comment]
@igreenfield I run it with exactly the same build - and I didn't notice this kind of error. You are using *.ignore v1.6*, right ?

**Comment by igreenfield** [comment]
![image](https://cloud.githubusercontent.com/assets/5586356/22736257/f4e10f7a-ee05-11e6-8317-95098ce2e83e.png)

**Comment by hsz** [comment]
Ok, one more question then - does this error also occurs after the IDE restart? Or it was just one-time glitch?

I have created a build with some probably fix. Can you install it from the zip package and verify if it's fixed?

> Settings > Plugins > Install plugin from disk...
[idea-gitignore-1.6.zip](https://github.com/hsz/idea-gitignore/files/760537/idea-gitignore-1.6.zip)

**Comment by igreenfield** [comment]
this happen after restart.

I will test.

**Comment by igreenfield** [comment]
with zip all working thanks....

**Comment by hsz** [comment]
@igreenfield Ok, thank you for the feedback. I'll deliver this fix with the next release. For now you can use this one, it will be replaced automatically when v1.7 will arrive.
