### ISSUE TITLE
NoSuchFieldError: GRAYED_SMALL_ATTRIBUTES

### ISSUE THREAD

**Issue by andrepolo** [hsz/idea-gitignore#305]
Since last update (minutes ago) i get this error:

```
GRAYED_SMALL_ATTRIBUTES
java.lang.NoSuchFieldError: GRAYED_SMALL_ATTRIBUTES
	at mobi.hsz.idea.gitignore.projectView.IgnoreViewNodeDecorator.decorate(IgnoreViewNodeDecorator.java:85)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode$1.run(AbstractPsiBasedNode.java:161)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:946)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:132)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:944)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:940)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:892)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3012)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33$1.run(AbstractTreeUi.java:1728)
	at com.intellij.ide.util.treeView.AbstractTreeUi$35.perform(AbstractTreeUi.java:1818)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1830)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1815)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5300(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$34.perform(AbstractTreeUi.java:1783)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2091)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:62)
	at com.intellij.ide.util.treeView.AbstractTreeUi$38$1.perform(AbstractTreeUi.java:1983)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2186)
	at com.intellij.ide.util.treeView.AbstractTreeUi$38.perform(AbstractTreeUi.java:1978)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:33)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:53)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder$1.process(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:99)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:58)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:866)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:654)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by andrepolo** [comment]
thx, phpstorm works again ;-)
