### ISSUE TITLE
NullPointerException on PhpStorm startup

### ISSUE THREAD

**Issue by rcapile** [hsz/idea-gitignore#315]
After installing gitignore 1.7.5, I get the following when launching PhpStorm.
PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

```
Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart PhpStorm.

java.lang.NullPointerException
    at mobi.hsz.idea.gitignore.IgnoreApplicationComponent.initComponent(IgnoreApplicationComponent.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:69)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by pschulten** [comment]
same here:
IntelliJ IDEA 2017.1 EAP
Build #IU-171.3019.7, built on February 7, 2017
IntelliJ IDEA EAP User
Expiration date: March 9, 2017
JRE: 1.8.0_112-release-b702 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.3

**Comment by dejan2609** [comment]
version **1.7.5** works as expected for me:
```
IntelliJ IDEA (Community Edition) 2017.1 EAP
Build #IC-171.3019.7, built on February 7, 2017
JRE: 1.8.0_121-b13 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
```

**Comment by martinezleoml** [comment]
It doesn't work for me:

```
WebStorm 2016.3.3
Build #WS-163.12024.17, built on January 31, 2017
Licensed to ***
Subscription is active until ***
For educational use only.
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

A had the same issue earlier with WebStorm (last version) on Windows but I don't have this computer at hand at the moment to post its WebStorm version.

**Comment by joaquingatica** [comment]
Doesn't work for me in version 1.7.5 on Android Studio:
```
Android Studio 2.2.3
Build #AI-145.3537739, built on December 2, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by dejan2609** [comment]
Me again.... version **1.7.5** works like a charm on **Android Studio 2.3 Beta 3 / Windows 10**:
```
Android Studio 2.3 Beta 3
Build #AI-162.3671887, built on January 25, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by mqwerty** [comment]
Also doesn't work:

```
PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016
JRE: 1.8.0_112-release-408-b6 x86
JVM: OpenJDK Server VM by JetBrains s.r.o
```

**Comment by snooze6** [comment]
Crashing for me too:

```
WebStorm 2016.3.3
Build #WS-163.12024.17, built on January 31, 2017
Subscription is active until <Someday>
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
On Linux, the stacktrace is the following:

```
Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.NullPointerException
    at mobi.hsz.idea.gitignore.IgnoreApplicationComponent.initComponent(IgnoreApplicationComponent.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:68)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by rcapile** [comment]
I have php Storm at home with version 2016.3.2 and worked. I updated to 2016.3.3 and still works.

But here at work it not working. Both are Ubuntu. Maybe a incompatibility with some other plugin?

PhpStorm 2016.3.1
Build #PS-163.9735.1, built on December 6, 2016
JRE: 1.8.0_112-release-408-b2 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016
JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by romic96** [comment]
Same here
PyCharm Community 2016.3.2

Older version is working

```
Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart PyCharm Community Edition.

java.lang.NullPointerException
    at mobi.hsz.idea.gitignore.IgnoreApplicationComponent.initComponent(IgnoreApplicationComponent.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:47)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```

**Comment by pschichtel** [comment]
The same happens in Android Studio

**Comment by rusAnthrax** [comment]
IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017

Crashes every time.

**Comment by auval** [comment]
same here in Android Studio 2.3 Beta 4, trying to freshly install .ignore 1.7.5

Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart Android Studio.

java.lang.NullPointerException
    at mobi.hsz.idea.gitignore.IgnoreApplicationComponent.initComponent(IgnoreApplicationComponent.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:518)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:119)
    at com.intellij.openapi.application.impl.ApplicationImpl.lambda$createComponents$8(ApplicationImpl.java:429)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:170)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:494)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:443)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:155)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:436)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:103)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:392)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:384)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:196)
    at com.intellij.idea.MainImpl$1.lambda$null$0(MainImpl.java:47)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:358)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by einnuj** [comment]
Same exact bug and stack-trace as OP, except for Intellij IDEA on macOS Sierra 10.12.3.

> IntelliJ IDEA 2016.3.4
Build #IU-163.12024.16, built on January 31, 2017
Licensed to Doctor Stranger
Subscription is active until November 15, 2017
JRE: 1.8.0_112-release-408-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by pedroadame** [comment]
It doesn't work. 
1.7.5 on Arch Linux with PhpStorm 2016.3 and 2017.1 EAP

**Comment by davidmpaz** [comment]
The same situation with me on Ubuntu 16.04 with PphStorm 2016.3

**Comment by hsz** [comment]
Finally after a quite long time of unexpected absence in this project I was able to go back to GitHub and release this bugfix.

*v1.7.6 has just arrived to the plugins repository*




_Because of a plenty of duplicates, I'll just call the others (upvoters, reporters, commenters...) to just let you know.

@abcoep @ahonymous @aimarchenko @akshaybabloo @andjelx @aliuspetraska @amiram  @c-jonua @derentenpopel @dericcain @Didldu-Florian @digish @dmlo @Erchard @epfremmer @evandertino @evgen-d @fatcats @gabrielgio @Grafe89 @Hexeption @hosseinkhaledi @ingvard @jason-chang @k4reln @keqingyuan @khs1994 @kraluk @krarey @mafzst @marcelopm @MarcelTon @mhz-tamb @minhphuc429 @mseleng @Nemmo @ngdo-pro @nunesvictor @OndrejSpanel @Pafishek @Pagestylist @pedroadame @philippe2803 @plombardi89 @planet17 @pymob @rcapile @RazorNd @rayk @RIP21 @sadig @sambadevi @ser-kletrov @skobeeffdev @snooze6 @sparsick @szewczyk-it @TangRufus @tonystatic @tknarr @Trak-X @trixanapp @Xhelas @XuluWarrior @yanzhenxiang @yizeliang @wangcongyi @wizaord @techstay @petenattress @mark-orussa @zeroarst @bllfrnch @martinezleoml @joaquingatica @dejan2609 @mqwerty @romic96 @pschichtel @rusAnthrax @auval @einnuj @davidmpaz

_

**Comment by hsz** [comment]
cc @abcoep @ahonymous @aimarchenko @akshaybabloo @andjelx @aliuspetraska @amiram  @c-jonua @derentenpopel @dericcain @Didldu-Florian @digish @dmlo @Erchard @epfremmer @evandertino @evgen-d @fatcats @gabrielgio @Grafe89 @Hexeption @hosseinkhaledi @ingvard @jason-chang @k4reln @keqingyuan @khs1994 @kraluk @krarey @mafzst @marcelopm @MarcelTon @mhz-tamb @minhphuc429 @mseleng @Nemmo @ngdo-pro @nunesvictor @OndrejSpanel @Pafishek @Pagestylist @pedroadame @philippe2803 @plombardi89 @planet17 @pymob @rcapile @RazorNd @rayk @RIP21 @sadig @sambadevi @ser-kletrov @skobeeffdev @snooze6 @sparsick @szewczyk-it @TangRufus @tonystatic @tknarr @Trak-X @trixanapp @Xhelas @XuluWarrior @yanzhenxiang @yizeliang @wangcongyi @wizaord @techstay @petenattress @mark-orussa @zeroarst @bllfrnch @martinezleoml @joaquingatica @dejan2609 @mqwerty @romic96 @pschichtel @rusAnthrax @auval @einnuj @davidmpaz

**Comment by hsz** [comment]
@sadig @sambadevi @ser-kletrov @skobeeffdev @snooze6 @sparsick @szewczyk-it @TangRufus @tonystatic @tknarr @Trak-X @trixanapp @Xhelas @XuluWarrior @yanzhenxiang @yizeliang @wangcongyi @wizaord @techstay @petenattress @mark-orussa @zeroarst @bllfrnch @martinezleoml @joaquingatica @dejan2609 @mqwerty @romic96 @pschichtel @rusAnthrax @auval @einnuj @davidmpaz

**Comment by Trak-X** [comment]
Perfect. No longer crashing my Android Studio. 👍

**Comment by joaquingatica** [comment]
@hsz Working like a charm! Thanks for the effort and the fast pace!

**Comment by szewczyk-it** [comment]
Intellij IDEA 2016.3.4 - fine. Thanks for fast update!

**Comment by kraluk** [comment]
@hsz big thanks for fix and update! Now everything is working perfectly :)
