### ISSUE TITLE
 IntelliJ IDEA crash

### ISSUE THREAD

**Issue by Erchard** [hsz/idea-gitignore#326]
Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart IntelliJ IDEA.

java.lang.NullPointerException
    at mobi.hsz.idea.gitignore.IgnoreApplicationComponent.initComponent(IgnoreApplicationComponent.java:59)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:68)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by Pagestylist** [comment]
Hi,
i have the same issue.
PhpStorm 2016.3.2

**Comment by Pafishek** [comment]
Hello, 
I have this issue too. But only with latest version. I needed the plugin on different computer and it doesn't work, but the older version (1.7.3) on my main computer works without a problem (update is available, but I won't try it for obvious reasons).

**Comment by evandertino** [comment]
This is urgent

**Comment by pymob** [comment]
I have this issue too!
IDEA 2016.3.4/64bit

**Comment by amiram** [comment]
Also for me. Webstorm 2016.3.3 Win10 64bit.

Plugin 'mobi.hsz.idea.gitignore' failed to initialize and will be disabled.  Please restart WebStorm.

java.lang.IllegalArgumentException: Argument for @NotNull parameter 'defaultValue' of com/intellij/util/ObjectUtils.notNull must not be null
    at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java)
    at com.intellij.util.ObjectUtils.notNull(ObjectUtils.java:74)
    at com.intellij.util.ObjectUtils.assertNotNull(ObjectUtils.java:35)
    at com.intellij.dvcs.repo.VcsRepositoryManager.getInstance(VcsRepositoryManager.java:61)
    at mobi.hsz.idea.gitignore.util.CacheMap.<init>(CacheMap.java:142)
    at mobi.hsz.idea.gitignore.IgnoreManager.<init>(IgnoreManager.java:282)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter$1.run(ConstructorInjectionComponentAdapter.java:220)
    at org.picocontainer.defaults.ThreadLocalCyclicDependencyGuard.observe(ThreadLocalCyclicDependencyGuard.java:53)
    at org.picocontainer.defaults.ConstructorInjectionComponentAdapter.getComponentInstance(ConstructorInjectionComponentAdapter.java:248)
    at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:58)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:478)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:96)
    at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:287)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.a(ProjectManagerImpl.java:222)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.c(ProjectManagerImpl.java:280)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:207)
    at com.intellij.openapi.project.impl.ProjectManagerImpl.getDefaultProject(ProjectManagerImpl.java:277)
    at com.intellij.ide.fileTemplates.FileTemplateManager.getDefaultInstance(FileTemplateManager.java:67)
    at com.intellij.ide.fileTemplates.FileTemplateManager.getInstance(FileTemplateManager.java:63)
    at com.dci.intellij.dbn.DatabaseNavigator.initComponent(DatabaseNavigator.java:60)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:501)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:125)
    at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:444)
    at com.intellij.openapi.progress.impl.CoreProgressManager$3.run(CoreProgressManager.java:179)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:568)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:519)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:164)
    at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:451)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:109)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:403)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:389)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:190)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:68)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by ingvard** [comment]
I have this issue too!
[   4357]  ERROR - rationStore.ComponentStoreImpl - IntelliJ IDEA 2016.1.4  Build #IU-145.2070.6 
[   4357]  ERROR - rationStore.ComponentStoreImpl - JDK: 1.8.0_76-release 
[   4358]  ERROR - rationStore.ComponentStoreImpl - VM: OpenJDK 64-Bit Server VM 
[   4358]  ERROR - rationStore.ComponentStoreImpl - Vendor: JetBrains s.r.o 
[   4358]  ERROR - rationStore.ComponentStoreImpl - OS: Linux 
[   6520]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException:  [Plugin: mobi.hsz.idea.gitignore] 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: com.intellij.diagnostic.PluginException:  [Plugin: mobi.hsz.idea.gitignore]
....

**Comment by wizaord** [comment]
Same issue with the community edition

**Comment by gabrielgio** [comment]
Same with WebStorm.

**Comment by tknarr** [comment]
I have it in IntelliJ IDEA Ultimate 2016.3.4, but not in RubyMine 2016.3.1.

**Comment by aliuspetraska** [comment]
same here with IntelliJ IDEA 2016.3.4

**Comment by c-jonua** [comment]
I have this bug too: IDEA 2017.1 EAP

**Comment by dericcain** [comment]
I have the same issue PhpStorm 2016.3.

**Comment by Xhelas** [comment]
Same issue on Android studio /Ubuntu 16.04/OpenJdk 1.8.

**Comment by sadig** [comment]
Same here with pycharm 2016.3.2 Pro Edition

**Comment by k4reln** [comment]
Same here (plugin version: 1.7.5)

PhpStorm 2016.3.2
Build #PS-163.10504.2, built on December 20, 2016

JRE: 1.8.0_112-release-408-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by Didldu-Florian** [comment]
Same here #328 Seems to be same issue

**Comment by Grafe89** [comment]
Same here

**Comment by sambadevi** [comment]
Same issue here, IntelliJ Ultimate 2016.3.4 and it looks like #330 is also the same

**Comment by hsz** [comment]
Thank you for the report. It has been already reported and fixed with #315
