### ISSUE TITLE
Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null

### ISSUE THREAD

**Issue by milas** [hsz/idea-gitignore#354]
Found in the IDE log -- wasn't doing anything special. Using .ignore plugin v1.7.6.

## IntelliJ
```
IntelliJ IDEA 2017.1.1
Build #IU-171.4073.35, built on April 6, 2017
JRE: 1.8.0_112-release-736-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.10.5
```

## Stack Trace
```
Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'directory' of mobi/hsz/idea/gitignore/util/Utils.getRelativePath must not be null
	at mobi.hsz.idea.gitignore.util.Utils.$$$reportNull$$$0(Utils.java)
	at mobi.hsz.idea.gitignore.util.Utils.getRelativePath(Utils.java)
	at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:285)
	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:321)
	at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:69)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.calcStatus(FileStatusManagerImpl.java:140)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.getStatus(FileStatusManagerImpl.java:275)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.getFileColor(FileEditorManagerImpl.java:368)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.updateFileColor(EditorsSplitters.java:378)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.e(FileEditorManagerImpl.java:399)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.access$1500(FileEditorManagerImpl.java:111)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyFileStatusListener.a(FileEditorManagerImpl.java:1780)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$MyFileStatusListener.b(FileEditorManagerImpl.java:1766)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:827)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment]
@milas Thank you for this report. This issue was related to the CacheMap component which will be completly removed in the next v2.0.0 release (I've started using native IDE's indexing instead).
