### ISSUE TITLE
Already disposed: com.intellij.util.messages.impl.MessageBusImpl@3fb6b9ad

### ISSUE THREAD

**Issue by b1rdex** [hsz/idea-gitignore#360]
I had two projects open in separate windows and this error was thrown when I closed one of them.

```
Already disposed: com.intellij.util.messages.impl.MessageBusImpl@3fb6b9ad; owner=Project C:/Users/Anatoly/Documents/GitHub/yii of class java.lang.String; disposed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.util.messages.impl.MessageBusImpl.checkNotDisposed(MessageBusImpl.java:303)
	at com.intellij.util.messages.impl.MessageBusImpl.syncPublisher(MessageBusImpl.java:223)
	at mobi.hsz.idea.gitignore.util.CacheMap$TrackedIgnoredFilesRunnable.run(CacheMap.java:374)
	at mobi.hsz.idea.gitignore.util.CacheMap$TrackedIgnoredFilesRunnable.run(CacheMap.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by YOzaz** [comment]
Happening to us as well, when switching projects.

```
Already disposed: com.intellij.util.messages.impl.MessageBusImpl@7d69e68a; owner=Project C:/www/win of class java.lang.String; disposed
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.util.messages.impl.MessageBusImpl.checkNotDisposed(MessageBusImpl.java:303)
	at com.intellij.util.messages.impl.MessageBusImpl.syncPublisher(MessageBusImpl.java:223)
	at mobi.hsz.idea.gitignore.util.CacheMap$TrackedIgnoredFilesRunnable.run(CacheMap.java:374)
	at mobi.hsz.idea.gitignore.util.CacheMap$TrackedIgnoredFilesRunnable.run(CacheMap.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hsz** [comment]
@b1rdex @YOzaz Thank you guys for reporting that. I got rid of the `CacheMap` class (for details see #367), so this issue will be automatically resolved with the next release which is finally on the horizon.
