### ISSUE TITLE
NPE in version v2.0.0-rc.1

### ISSUE THREAD

**Issue by tobias-** [hsz/idea-gitignore#372]
```
2017-06-13 10:34:17,785 [54223752]  ERROR - llij.ide.plugins.PluginManager - null 
java.lang.NullPointerException
        at mobi.hsz.idea.gitignore.lang.kind.FossilLanguage$1.fetch(FossilLanguage.java:59)
        at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalFiles(ExternalIndexableSetContributor.java:72)
        at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalProjectRootsToIndex(ExternalIndexableSetContributor.java:87)
        at com.intellij.util.indexing.IndexableSetContributor.getProjectRootsToIndex(IndexableSetContributor.java:38)
        at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.collectScanRootRunnables(FileBasedIndexScanRunnableCollectorImpl.java:91)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:2240)
        at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2232)
        at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1049)
        at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:899)
        at com.intellij.util.indexing.FileBasedIndexImpl.processValues(FileBasedIndexImpl.java:786)
        at com.intellij.psi.search.FileNameIndexServiceImpl.getVirtualFilesByName(FileNameIndexServiceImpl.java:40)
        at com.intellij.psi.search.FilenameIndex.getVirtualFilesByName(FilenameIndex.java:65)
        at com.intellij.javascript.nodejs.util.NodePackage.lambda$collectAvailableNodePackages$1(NodePackage.java:179)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
        at com.intellij.javascript.nodejs.util.NodePackage.collectAvailableNodePackages(NodePackage.java:179)
        at com.intellij.javascript.nodejs.util.NodePackage.lambda$findPreferredPackage$0(NodePackage.java:142)
        at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
        at com.intellij.javascript.nodejs.util.NodePackage.findPreferredPackage(NodePackage.java:141)
        at com.intellij.javascript.nodejs.util.NodePackage.findPreferredPackage(NodePackage.java:133)
        at com.intellij.lang.javascript.boilerplate.NpmPackageProjectGenerator$NpmPackageGeneratorPeer.createPanel(NpmPackageProjectGenerator.java:267)
        at com.intellij.lang.javascript.boilerplate.NpmPackageProjectGenerator$NpmPackageGeneratorPeer.<init>(NpmPackageProjectGenerator.java:248)
        at com.intellij.lang.javascript.boilerplate.NpmPackageProjectGenerator.createPeer(NpmPackageProjectGenerator.java:213)
        at com.intellij.lang.javascript.boilerplate.NpmPackageProjectGenerator.createPeer(NpmPackageProjectGenerator.java:66)
        at com.intellij.platform.DirectoryProjectGenerator$1.compute(DirectoryProjectGenerator.java:77)
        at com.intellij.platform.DirectoryProjectGenerator$1.compute(DirectoryProjectGenerator.java:73)
        at com.intellij.openapi.util.NotNullLazyValue.getValue(NotNullLazyValue.java:39)
        at com.intellij.openapi.module.WebModuleBuilder.<init>(WebModuleBuilder.java:48)
        at com.intellij.openapi.module.WebModuleType.createModuleBuilder(WebModuleType.java:24)
        at com.intellij.ide.util.projectWizard.WebProjectTemplate.createModuleBuilder(WebProjectTemplate.java:36)
        at com.intellij.ide.util.projectWizard.WebProjectTemplate.createModuleBuilder(WebProjectTemplate.java:32)
        at com.intellij.ide.projectWizard.ProjectTypeStep$1.create(ProjectTypeStep.java:99)
        at com.intellij.ide.projectWizard.ProjectTypeStep$1.create(ProjectTypeStep.java:95)
        at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:57)
        at com.intellij.ide.projectWizard.ProjectTypeStep.<init>(ProjectTypeStep.java:227)
        at com.intellij.ide.projectWizard.NewProjectWizard.init(NewProjectWizard.java:49)
        at com.intellij.ide.projectWizard.NewProjectWizard.<init>(NewProjectWizard.java:39)
        at com.intellij.openapi.roots.ui.configuration.actions.NewModuleAction.actionPerformed(NewModuleAction.java:58)
        at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:216)
        at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:233)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.a(ActionMenuItem.java:310)
        at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:911)
        at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:136)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:300)
        at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.a(ActionMenuItem.java:117)
        at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
        at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
        at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
        at com.intellij.openapi.application.TransactionGuard.submitTransaction(TransactionGuard.java:122)
        at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:117)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.a(BegMenuItemUI.java:513)
        at com.intellij.ui.plaf.beg.BegMenuItemUI.access$300(BegMenuItemUI.java:45)
        at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:533)
        at java.awt.Component.processMouseEvent(Component.java:6541)
        at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
        at java.awt.Component.processEvent(Component.java:6306)
        at java.awt.Container.processEvent(Container.java:2237)
        at java.awt.Component.dispatchEventImpl(Component.java:4897)
        at java.awt.Container.dispatchEventImpl(Container.java:2295)
        at java.awt.Component.dispatchEvent(Component.java:4719)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4889)
        at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4526)
        at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4467)
        at java.awt.Container.dispatchEventImpl(Container.java:2281)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4719)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
        at java.awt.EventQueue.access$500(EventQueue.java:98)
        at java.awt.EventQueue$3.run(EventQueue.java:715)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:737)
        at java.awt.EventQueue$4.run(EventQueue.java:735)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
        at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
        at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:645)
        at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by filiphr** [comment]
@hsz I am also having issues with this NPE. One can't create new modules in a project. Do you know when you are going to publish the release? Do you have plans for rc2 soon?
