### ISSUE TITLE
"Show ignored files" is buggy

### ISSUE THREAD

**Issue by doxxx** [hsz/idea-gitignore#38]
Using IDEA EAP 138.1024 and gitignore plugin 0.5.1.

The title for the "Show ignored files" popup dialog starts with a `"` character and ends with the word "null". So it looks like:

```
"Ignored files for: null
```

There appears to be an associated exception:

```
update failed for AnAction with ID=Gitignore.IgnoreGroup
java.lang.NullPointerException
	at mobi.hsz.idea.gitignore.util.Utils.getSuitableGitignoreFiles(Utils.java:81)
	at mobi.hsz.idea.gitignore.actions.IgnoreFileGroupAction.update(IgnoreFileGroupAction.java:35)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:113)
	at com.intellij.openapi.actionSystem.impl.Utils.doUpdate(Utils.java:187)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:138)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:85)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu(Utils.java:279)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:96)
	at com.intellij.ide.ui.customization.CustomizationUtil$3.invokePopup(CustomizationUtil.java:291)
	at com.intellij.ui.PopupHandler.mouseReleased(PopupHandler.java:55)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
	at java.awt.Component.processMouseEvent(Component.java:6527)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3321)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:418)
	at com.intellij.ide.dnd.aware.DnDAwareTree.processMouseEvent(DnDAwareTree.java:52)
	at java.awt.Component.processEvent(Component.java:6292)
	at java.awt.Container.processEvent(Container.java:2234)
	at java.awt.Component.dispatchEventImpl(Component.java:4883)
	at java.awt.Container.dispatchEventImpl(Container.java:2292)
	at java.awt.Component.dispatchEvent(Component.java:4705)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4898)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4533)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4462)
	at java.awt.Container.dispatchEventImpl(Container.java:2278)
	at java.awt.Window.dispatchEventImpl(Window.java:2739)
	at java.awt.Component.dispatchEvent(Component.java:4705)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:746)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:719)
	at java.awt.EventQueue$4.run(EventQueue.java:717)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:716)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:722)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:545)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:360)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

It also appears to be showing every file in my working directory as ignored, when that is clearly not the case.

**Comment by hsz** [comment]
"Show ignored files" dialog has been removed. With new release `v0.10` ignored files will be marked with gray color in the Project View tree.
