### ISSUE TITLE
Conflict with Google's Google Cloud Tools

### ISSUE THREAD

**Issue by bamapookie** [hsz/idea-gitignore#386]
Starting with IntelliJ 2017.2 Public Preview and still occurring in Release Candidate 2, IntelliJ started reporting that the .ignore (1.7.6) and Google Cloud Tools (17.6.2) plugins conflict.  One or both must be disabled to continue.

IntelliJ details:
IntelliJ IDEA 2017.2
Build #IU-172.3317.53, built on July 12, 2017
JRE: 1.8.0_152-release-915-b5 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.5

Exception from the logs:
2017-07-13 13:29:14,005 [   5313]  ERROR - llij.ide.plugins.PluginManager - com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.google.gct.core 
java.lang.RuntimeException: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.google.gct.core
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:210)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.idea.MainImpl$1$1.a(MainImpl.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:345)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: com.intellij.ide.plugins.PluginManager$StartupAbortedException: Fatal error initializing plugin com.google.gct.core
	at com.intellij.ide.plugins.PluginManager.handleComponentError(PluginManager.java:254)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:310)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.<init>(FileTypeManagerImpl.java:267)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.defaults.InstantiatingComponentAdapter.newInstance(InstantiatingComponentAdapter.java:193)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.doGetComponentInstance(CachingConstructorInjectionComponentAdapter.java:103)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.instantiateGuarded(CachingConstructorInjectionComponentAdapter.java:80)
	at com.intellij.util.pico.CachingConstructorInjectionComponentAdapter.getComponentInstance(CachingConstructorInjectionComponentAdapter.java:63)
	at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentConfigComponentAdapter.getComponentInstance(ComponentManagerImpl.java:469)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.createComponents(ComponentManagerImpl.java:118)
	at com.intellij.openapi.application.impl.ApplicationImpl.a(ApplicationImpl.java:475)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.application.impl.ApplicationImpl.createComponents(ApplicationImpl.java:482)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:102)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:434)
	at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:420)
	at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:203)
	... 20 more
Caused by: com.intellij.diagnostic.PluginException:  [Plugin: com.google.gct.core]
	... 44 more
Caused by: java.lang.ExceptionInInitializerError
	at com.google.cloud.tools.intellij.appengine.file.DockerFileTemplateType.<init>(DockerFileTemplateType.java:39)
	at com.google.cloud.tools.intellij.appengine.file.DockerFileTemplateType.<clinit>(DockerFileTemplateType.java:35)
	at com.google.cloud.tools.intellij.appengine.file.DockerFileTemplateTypeFactory.createFileTypes(DockerFileTemplateTypeFactory.java:31)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.initStandardFileTypes(FileTypeManagerImpl.java:307)
	... 42 more
Caused by: com.intellij.diagnostic.ImplementationConflictException: Language with ID 'Docker' is already registered: class mobi.hsz.idea.gitignore.lang.kind.DockerLanguage
	at com.intellij.lang.Language.<init>(Language.java:89)
	at com.intellij.lang.Language.<init>(Language.java:73)
	at com.intellij.lang.Language.<init>(Language.java:69)
	at com.google.cloud.tools.intellij.appengine.file.DockerFileTemplateLanguage.<init>(DockerFileTemplateLanguage.java:29)
	at com.google.cloud.tools.intellij.appengine.file.DockerFileTemplateLanguage.<clinit>(DockerFileTemplateLanguage.java:26)
	... 46 more

**Comment by bamapookie** [comment]
Nevermind.  Already fixed on Google's side: https://github.com/GoogleCloudPlatform/google-cloud-intellij/issues/1535
