### ISSUE TITLE
Gogland IDE freezes at EDT

### ISSUE THREAD

**Issue by junchaowu** [hsz/idea-gitignore#387]
```
"AWT-EventQueue-0 1.0#GO-171.4694.35 Gogland, eap:true, os:Mac OS X 10.11.6, java-version:JetBrains s.r.o 1.8.0_112-release-736-b21" #46 prio=6 os_prio=31 tid=0x00007fb3e226e000 nid=0xec0b runnable [0x0000700002821000]
   java.lang.Thread.State: RUNNABLE
       	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.copyString(VirtualFileSystemEntry.java:180)
       	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:173)
       	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:170)
       	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:170)
       	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.appendPathOnFileSystem(VirtualFileSystemEntry.java:170)
       	at com.intellij.openapi.vfs.newvfs.impl.VirtualFileSystemEntry.getPath(VirtualFileSystemEntry.java:197)
       	at mobi.hsz.idea.gitignore.util.Utils$1.compare(Utils.java:435)
       	at mobi.hsz.idea.gitignore.util.Utils$1.compare(Utils.java:432)
       	at java.util.TimSort.mergeLo(TimSort.java:717)
       	at java.util.TimSort.mergeAt(TimSort.java:514)
       	at java.util.TimSort.mergeCollapse(TimSort.java:439)
       	at java.util.TimSort.sort(TimSort.java:245)
       	at java.util.Arrays.sort(Arrays.java:1512)
       	at java.util.ArrayList.sort(ArrayList.java:1454)
       	at java.util.Collections.sort(Collections.java:175)
       	at com.intellij.util.containers.ContainerUtil.sort(ContainerUtil.java:1725)
       	at mobi.hsz.idea.gitignore.util.Utils.ignoreFilesSort(Utils.java:432)
       	at mobi.hsz.idea.gitignore.util.CacheMap.isFileIgnored(CacheMap.java:267)
       	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:321)
       	at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:69)
       	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.calcStatus(FileStatusManagerImpl.java:140)
       	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.getStatus(FileStatusManagerImpl.java:275)
       	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.b(LineStatusTrackerManager.java:269)
       	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:244)
       	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:238)
       	- locked <0x00000007aa39e8f0> (a java.lang.Object)
       	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.b(LineStatusTrackerManager.java:217)
       	- locked <0x00000007aa39e8f0> (a java.lang.Object)
       	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.access$1600(LineStatusTrackerManager.java:67)
       	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager$MyFileStatusListener.fileStatusesChanged(LineStatusTrackerManager.java:419)
       	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.fileStatusesChanged(FileStatusManagerImpl.java:216)
       	at mobi.hsz.idea.gitignore.util.CacheMap.refresh(CacheMap.java:194)
       	at mobi.hsz.idea.gitignore.util.CacheMap.cleanup(CacheMap.java:180)
       	at mobi.hsz.idea.gitignore.IgnoreManager$1.fileDeleted(IgnoreManager.java:171)
       	at sun.reflect.GeneratedMethodAccessor51.invoke(Unknown Source)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
       	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
       	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
       	at com.sun.proxy.$Proxy23.fileDeleted(Unknown Source)
       	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:85)
       	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
       	at sun.reflect.GeneratedMethodAccessor53.invoke(Unknown Source)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:498)
       	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
       	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:437)
       	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:398)
       	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
       	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:373)
       	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:44)
       	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:230)
       	at com.sun.proxy.$Proxy24.after(Unknown Source)
       	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:779)
       	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.c(RefreshSessionImpl.java:196)
       	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl$$Lambda$67/116376225.run(Unknown Source)
       	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
       	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:183)
       	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$728/55321739.run(Unknown Source)
       	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
       	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
       	at com.intellij.openapi.application.TransactionGuardImpl$$Lambda$229/988166912.run(Unknown Source)
       	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:118)
       	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl.a(RefreshQueueImpl.java:81)
       	at com.intellij.openapi.vfs.newvfs.RefreshQueueImpl$$Lambda$332/1714560023.run(Unknown Source)
       	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:303)
       	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:410)
       	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
       	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
       	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
       	at java.awt.EventQueue.access$500(EventQueue.java:98)
       	at java.awt.EventQueue$3.run(EventQueue.java:715)
       	at java.awt.EventQueue$3.run(EventQueue.java:709)
       	at java.security.AccessController.doPrivileged(Native Method)
       	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
       	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
       	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:827)
       	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:655)
       	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
       	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
       	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
       	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
       	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
       	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
       	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by junchaowu** [comment]
Mention @ignatov here.

**Comment by ignatov** [comment]
Hi, @hsz, it's a kind of blocker for many users, they're suffering from freezing IntelliJ, WebStorm, and other IDEs. They just say: "my IDE is unresponsible and I'm going back to notepad.exe, vim, or another fast editor."

Could you please move all heavy activities to the separate thread?

**Comment by hsz** [comment]
@junchaowu @ignatov Everything is about the `CacheMap` component which was completly removed in the forthcoming v2.0.
