### ISSUE TITLE
Exception while opening project (2.0)

### ISSUE THREAD

**Issue by xaviergonz** [hsz/idea-gitignore#394]
After updating to v2.0, after the second time I opened the project this exception always appears

```
Error while indexing XXX\node_modules\browserify-incremental\.eslintignore
To reindex this file IDEA has to be restarted: @NotNull method com/intellij/util/indexing/FileContentImpl.createFileFromText must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/util/indexing/FileContentImpl.createFileFromText must not return null
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:143)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:135)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:104)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:88)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:61)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by hsz** [comment]
What version of IDE do you use?

**Comment by hsz** [comment]
@xaviergonz Ok, I have found the reason of this issue. Thanks! It'll be released in a minutes with v2.0.1

**Comment by hsz** [comment]
@xaviergonz Can you confirm taht v2.0.1 resolves this issue?

**Comment by Kansuler** [comment]
I also had this issue, and it seems to have disappeared with v2.0.1

**Comment by yukikaoru** [comment]
I had same error on v2.0.4. Should I open another issue?
```
Error while indexing xxx/.stylelintignore
To reindex this file IDEA has to be restarted: @NotNull method com/intellij/util/indexing/FileContentImpl.createFileFromText must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/util/indexing/FileContentImpl.createFileFromText must not return null
```

**Comment by ogonkov** [comment]
Same error to @yukikaoru 

```
Error while indexing /foo/bar/.stylelintignore
To reindex this file IDEA has to be restarted: @NotNull method com/intellij/util/indexing/FileContentImpl.createFileFromText must not return null
java.lang.IllegalStateException: @NotNull method com/intellij/util/indexing/FileContentImpl.createFileFromText must not return null
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:143)
	at com.intellij.util.indexing.FileContentImpl.createFileFromText(FileContentImpl.java:135)
	at com.intellij.util.indexing.FileContentImpl.getPsiFile(FileContentImpl.java:104)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:85)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.map(IgnoreFilesIndex.java:58)
	at com.intellij.util.indexing.impl.MapReduceIndex.mapInput(MapReduceIndex.java:272)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:99)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.UnindexedFilesUpdater.a(UnindexedFilesUpdater.java:105)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:229)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1161)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.a(CacheUpdateRunner.java:246)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:157)
	at com.intellij.openapi.project.CacheUpdateRunner$MyRunnable.run(CacheUpdateRunner.java:242)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:343)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Zephir77167** [comment]
Hey, same error on .stylelintignore
