### ISSUE TITLE
Can't hide unversioned files 

### ISSUE THREAD

**Issue by AbdElraoufSabri** [hsz/idea-gitignore#399]
Got this exception and can't hide ignored files from project

```
Error executing task mobi.hsz.idea.gitignore.outer.OuterIgnoreLoaderComponent$IgnoreEditorManagerListener$1@bcfce4d
java.lang.UnsupportedOperationException
	at java.util.AbstractList.add(AbstractList.java:148)
	at java.util.AbstractList.add(AbstractList.java:108)
	at com.intellij.util.containers.ContainerUtil.addAllNotNull(ContainerUtil.java:741)
	at com.intellij.util.containers.ContainerUtil.addAllNotNull(ContainerUtil.java:731)
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreLoaderComponent$IgnoreEditorManagerListener$1.run(OuterIgnoreLoaderComponent.java:127)
	at com.intellij.openapi.project.DumbServiceImpl.e(DumbServiceImpl.java:296)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.b(TransactionGuardImpl.java:72)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment]
@AbdElraoufSabri what version of IDE / plugin do you use?

**Comment by AbdElraoufSabri** [comment]
I'm using IntellijIdea 2017.2 Ultimate. and tried with v2.0.4 and also v2.0.3 from Releases

**Comment by hsz** [comment]
Ok, thank you. I'll take care of it soon!

**Comment by gganssauge** [comment]
I have the same problem while importing a maven project with several submodules. There were no intellij project files whatsoever.
I'm using intellij 2017.2.1 ultimate.
