### ISSUE TITLE
Hundred of "update failed for AnAction with ..."

### ISSUE THREAD

**Issue by sciamannikoo** [hsz/idea-gitignore#414]
I'm getting hundred of IDE fatal errors which are having side effects like the inability to open a file from the project pane, seeing the content of a directory, selecting text, etc.

The issue has been around for several days and I naively thought the author would have noticed and solved, but it looks I must report it after all :)

This seems a regression of #43 (at least for what concerns the thrown error):

```
update failed for AnAction with ID=Compare.SameVersion: Unexpected termination offset for lexer com.jetbrains.php.lang.highlighter.PhpHighlightingLexer@2fc44b7d
java.lang.IllegalStateException: Unexpected termination offset for lexer com.jetbrains.php.lang.highlighter.PhpHighlightingLexer@2fc44b7d
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.a(LexerEditorHighlighter.java:388)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:354)
	at com.intellij.openapi.editor.ex.util.LayeredLexerEditorHighlighter.setText(LayeredLexerEditorHighlighter.java:136)
	at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:167)
	at com.intellij.psi.impl.cache.impl.id.PlatformIdTableBuilding$TokenSetTodoIndexer.map(PlatformIdTableBuilding.java:144)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:107)
	at com.intellij.psi.impl.cache.impl.todo.TodoIndex$4.map(TodoIndex.java:99)
	at com.intellij.util.indexing.SnapshotInputMappings.readPersistentDataOrMap(SnapshotInputMappings.java:149)
	at com.intellij.util.indexing.VfsAwareMapReduceIndex.calculateUpdateData(VfsAwareMapReduceIndex.java:95)
	at com.intellij.util.indexing.impl.MapReduceIndex.update(MapReduceIndex.java:215)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1615)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1551)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.freezeFileTypeTemporarilyIn(FileTypeManagerImpl.java:518)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1510)
	at com.intellij.util.indexing.FileBasedIndexImpl.indexFileContent(FileBasedIndexImpl.java:1498)
	at com.intellij.util.indexing.FileBasedIndexImpl.processRefreshedFile(FileBasedIndexImpl.java:1477)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1633)
	at com.intellij.util.indexing.FileBasedIndexImpl$VirtualFileUpdateTask.doProcess(FileBasedIndexImpl.java:1630)
	at com.intellij.util.indexing.UpdateTask.a(UpdateTask.java:80)
	at com.intellij.util.indexing.UpdateTask.processAll(UpdateTask.java:47)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:1652)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:696)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:662)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:609)
	at com.intellij.util.indexing.FileBasedIndexImpl.processAllKeys(FileBasedIndexImpl.java:598)
	at com.intellij.util.indexing.FileBasedIndexImpl.getAllKeys(FileBasedIndexImpl.java:592)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getKeys(IgnoreFilesIndex.java:204)
	at mobi.hsz.idea.gitignore.IgnoreManager.isFileIgnored(IgnoreManager.java:287)
	at mobi.hsz.idea.gitignore.vcs.IgnoreFileStatusProvider.getFileStatus(IgnoreFileStatusProvider.java:70)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.calcStatus(FileStatusManagerImpl.java:135)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.getStatus(FileStatusManagerImpl.java:248)
	at com.intellij.openapi.vcs.AbstractVcs.fileInVcsByFileStatus(AbstractVcs.java:271)
	at com.intellij.openapi.vcs.AbstractVcs.fileInVcsByFileStatus(AbstractVcs.java:267)
	at com.intellij.openapi.vcs.actions.AbstractShowDiffAction.a(AbstractShowDiffAction.java:83)
	at com.intellij.openapi.vcs.actions.AbstractShowDiffAction.isEnabled(AbstractShowDiffAction.java:71)
	at com.intellij.openapi.vcs.actions.AbstractShowDiffAction.updateDiffAction(AbstractShowDiffAction.java:48)
	at com.intellij.openapi.vcs.actions.AbstractShowDiffAction.update(AbstractShowDiffAction.java:42)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction.performUpdate(AbstractVcsAction.java:71)
	at com.intellij.openapi.vcs.actions.AbstractVcsAction.update(AbstractVcsAction.java:43)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:132)
	at com.intellij.openapi.actionSystem.impl.Utils.a(Utils.java:235)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:180)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:205)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:205)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroup(Utils.java:123)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.a(ActionToolbarImpl.java:974)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$000(ActionToolbarImpl.java:61)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$2.updateActionsImpl(ActionToolbarImpl.java:180)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.java:186)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:643)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.n(FocusManagerImpl.java:624)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.l(FocusManagerImpl.java:594)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:476)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2760)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.a(ToolbarUpdater.java:108)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.access$400(ToolbarUpdater.java:40)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyTimerListener.run(ToolbarUpdater.java:158)
	at com.intellij.openapi.actionSystem.impl.WeakTimerListener.run(WeakTimerListener.java:54)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1402)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.a(ActionManagerImpl.java:1392)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl$MyTimer.actionPerformed(ActionManagerImpl.java:1376)
	at javax.swing.Timer.fireActionPerformed(Timer.java:313)
	at javax.swing.Timer$DoPostEvent.run(Timer.java:245)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by hsz** [comment]
@sciamannikoo Thanks for the report. To be honest - I didn't notice this kind of error.

Can you please check if this issue is resolved with v2.1.0-RC.1 ?

**Comment by IceMan81** [comment]
@hsz This is an issue with v2.1.0. I just updated to the latest plugin and now navigation to files, classes etc, is broken (cannot use Ctrl + N to open a class). 
Intellij version: 2017.2.3

**Comment by hsz** [comment]
@IceMan81 Can you please paste the stack trace?

**Comment by hsz** [comment]
@sciamannikoo @IceMan81 

 Can you please write down some steps to reproduce? I couldn't get this error with IntelliJ 2017.2.2 nor 2017.2.3

In first stacktrace we can see ` com.jetbrains.php.lang.highlighter.PhpHighlightingLexer`.
Is it a JetBrains PHP plugin or you use another third party PHP plugins?
