### ISSUE TITLE
Invalid root jar

### ISSUE THREAD

**Issue by 1kastner** [hsz/idea-gitignore#418]
After an upgrade of a python package via pip I received the following fatal error in IntelliJ PyCharm:

    Invalid root jar://E:/path/to/miniconda/Lib/site-packages/cluster-1.3.3-py3.6.egg!/ in my_project -> < Python 3.6.0 (E:\path\to\miniconda\python.exe) >

The egg was supposed to be deleted as the new version now is 1.4.

**Comment by hsz** [comment]
@1kastner thanks for this report.

Can you please paste here a full stacktrace?

**Comment by 1kastner** [comment]
Sadly there was no stacktrace available in the GUI and I did not manage to reproduce the error.

**Comment by tim-mitchell** [comment]
I had a similar problem:

Invalid root file://S:/Leapfrog/win64/lib/python2.7 in Leapfrog-git -> < Python 2.7 >
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.roots.impl.RootIndex.a(RootIndex.java:225)
	at com.intellij.openapi.roots.impl.RootIndex.a(RootIndex.java:158)
	at com.intellij.openapi.roots.impl.RootIndex.<init>(RootIndex.java:74)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.d(DirectoryIndexImpl.java:113)
	at com.intellij.openapi.roots.impl.DirectoryIndexImpl.getInfoForFile(DirectoryIndexImpl.java:148)
	at com.intellij.openapi.roots.impl.FileIndexBase.getInfoForFileOrDirectory(FileIndexBase.java:79)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:107)
	at com.intellij.openapi.roots.impl.ProjectFileIndexImpl.getModuleForFile(ProjectFileIndexImpl.java:100)
	at com.intellij.openapi.module.ModuleUtilCore.findModuleForFile(ModuleUtilCore.java:74)
	at com.intellij.openapi.vcs.impl.ModuleDefaultVcsRootPolicy.getMatchContext(ModuleDefaultVcsRootPolicy.java:113)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.getMappingFor(NewMappings.java:220)
	at com.intellij.openapi.vcs.impl.projectlevelman.NewMappings.getVcsFor(NewMappings.java:248)
	at com.intellij.openapi.vcs.impl.ProjectLevelVcsManagerImpl.getVcsFor(ProjectLevelVcsManagerImpl.java:278)
	at com.intellij.openapi.vcs.impl.VcsFileStatusProvider.c(VcsFileStatusProvider.java:183)
	at com.intellij.openapi.vcs.impl.VcsFileStatusProvider.isSupported(VcsFileStatusProvider.java:179)
	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:266)
	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:242)
	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.a(LineStatusTrackerManager.java:211)
	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager.access$1000(LineStatusTrackerManager.java:56)
	at com.intellij.openapi.vcs.impl.LineStatusTrackerManager$MyFileStatusListener.fileStatusesChanged(LineStatusTrackerManager.java:416)
	at com.intellij.openapi.vcs.impl.FileStatusManagerImpl.fileStatusesChanged(FileStatusManagerImpl.java:194)
	at mobi.hsz.idea.gitignore.util.CacheMap.refresh(CacheMap.java:194)
	at mobi.hsz.idea.gitignore.util.CacheMap.cleanup(CacheMap.java:180)
	at mobi.hsz.idea.gitignore.IgnoreManager$1.fileDeleted(IgnoreManager.java:171)
	at sun.reflect.GeneratedMethodAccessor82.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy19.fileDeleted(Unknown Source)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.fireAfter(BulkVirtualFileListenerAdapter.java:85)
	at com.intellij.openapi.vfs.impl.BulkVirtualFileListenerAdapter.after(BulkVirtualFileListenerAdapter.java:56)
	at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:374)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy20.after(Unknown Source)
	at com.intellij.openapi.vfs.newvfs.persistent.PersistentFSImpl.processEvents(PersistentFSImpl.java:774)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.a(RefreshSessionImpl.java:196)
	at com.intellij.openapi.application.WriteAction.run(WriteAction.java:91)
	at com.intellij.openapi.vfs.newvfs.RefreshSessionImpl.fireEvents(RefreshSessionImpl.java:183)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:86)
	at com.intellij.openapi.application.TransactionGuardImpl.a(TransactionGuardImpl.java:109)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:416)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:399)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.b(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

I presumed this happened when S://Leapfrog/win64 folder (which is ignored) was deleted.

**Comment by 1kastner** [comment]
1.7.6, the default version in my editor. I have never refused an update when the plugin manager asked me to. Since the incident the error message has never popped up again, the plugin seems to work smoothly as expected.

**Comment by hsz** [comment]
@1kastner ok, so this issue should be automatically gone with the new release (currently 2.x are blacklisted and removed because of the performance issues - #408).
v2.1.0 should be released this week
