### ISSUE TITLE
Write-unsafe context! Model changes are allowed from write-safe contexts only.

### ISSUE THREAD

**Issue by zman0900** [hsz/idea-gitignore#471]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

After upgrading to .ignore plugin 2.2.0 and restarting IntelliJ idea 2017.2.3, an error is produced on startup:

> Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.

```
Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities={ModalityState.NON_MODAL=true, ModalityState:Loading Project 208202559: running=false; canceled=false=true}
java.lang.Throwable
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:132)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:230)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.fireEvent(PsiModificationTrackerImpl.java:73)
	at com.intellij.psi.impl.PsiModificationTrackerImpl.treeChanged(PsiModificationTrackerImpl.java:100)
	at com.intellij.psi.impl.PsiManagerImpl.fireEvent(PsiManagerImpl.java:368)
	at com.intellij.psi.impl.PsiManagerImpl.beforePropertyChange(PsiManagerImpl.java:284)
	at com.intellij.psi.impl.file.impl.FileManagerImpl$FileTypesChanged.run(FileManagerImpl.java:328)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1030)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.handleFileTypesChange(FileManagerImpl.java:341)
	at com.intellij.psi.impl.file.impl.FileManagerImpl.processFileTypesChanged(FileManagerImpl.java:313)
	at com.intellij.psi.impl.file.impl.PsiVFSListener$2.fileTypesChanged(PsiVFSListener.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy98.beforePsiChanged(Unknown Source)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChange(PsiManagerImpl.java:470)
	at com.intellij.psi.impl.PsiManagerImpl.dropResolveCaches(PsiManagerImpl.java:110)
	at com.intellij.psi.impl.PsiManagerImpl.dropPsiCaches(PsiManagerImpl.java:116)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.a(ProjectRootManagerImpl.java:405)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:53)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.a(ProjectRootManagerImpl.java:104)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:117)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.c(ProjectRootManagerComponent.java:152)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.access$100(ProjectRootManagerComponent.java:67)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$1.fileTypesChanged(ProjectRootManagerComponent.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:381)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:372)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy98.beforePsiChanged(Unknown Source)
	at com.intellij.psi.impl.PsiManagerImpl.beforeChange(PsiManagerImpl.java:470)
	at com.intellij.psi.impl.PsiManagerImpl.dropResolveCaches(PsiManagerImpl.java:110)
	at com.intellij.psi.impl.PsiManagerImpl.dropPsiCaches(PsiManagerImpl.java:116)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.a(ProjectRootManagerImpl.java:405)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl.access$100(ProjectRootManagerImpl.java:53)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.a(ProjectRootManagerImpl.java:104)
	at com.intellij.openapi.roots.impl.ProjectRootManagerImpl$BatchSession.rootsChanged(ProjectRootManagerImpl.java:117)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.c(ProjectRootManagerComponent.java:152)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent.access$100(ProjectRootManagerComponent.java:67)
	at com.intellij.openapi.roots.impl.ProjectRootManagerComponent$1.fileTypesChanged(ProjectRootManagerComponent.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:443)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:404)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:393)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:374)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy125.fileTypesChanged(Unknown Source)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.fireFileTypesChanged(FileTypeManagerImpl.java:1035)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.associate(FileTypeManagerImpl.java:1478)
	at com.intellij.openapi.fileTypes.impl.FileTypeManagerImpl.associate(FileTypeManagerImpl.java:1016)
	at mobi.hsz.idea.gitignore.IgnoreManager$8.run(IgnoreManager.java:409)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1030)
	at mobi.hsz.idea.gitignore.IgnoreManager.associateFileType(IgnoreManager.java:406)
	at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalFiles(ExternalIndexableSetContributor.java:82)
	at mobi.hsz.idea.gitignore.indexing.IgnoreSearchScope.get(IgnoreSearchScope.java:57)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getEntries(IgnoreFilesIndex.java:231)
	at mobi.hsz.idea.gitignore.indexing.IgnoreFilesIndex.getFiles(IgnoreFilesIndex.java:249)
	at mobi.hsz.idea.gitignore.lang.kind.GitLanguage.getOuterFiles(GitLanguage.java:107)
	at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalFiles(ExternalIndexableSetContributor.java:77)
	at mobi.hsz.idea.gitignore.indexing.ExternalIndexableSetContributor.getAdditionalProjectRootsToIndex(ExternalIndexableSetContributor.java:102)
	at com.intellij.util.indexing.IndexableSetContributor.getProjectRootsToIndex(IndexableSetContributor.java:38)
	at com.intellij.util.indexing.FileBasedIndexScanRunnableCollectorImpl.collectScanRootRunnables(FileBasedIndexScanRunnableCollectorImpl.java:87)
	at com.intellij.util.indexing.FileBasedIndexImpl.a(FileBasedIndexImpl.java:2246)
	at com.intellij.util.indexing.FileBasedIndexImpl.iterateIndexableFiles(FileBasedIndexImpl.java:2238)
	at com.intellij.util.indexing.FileBasedIndexImpl.projectIndexableFiles(FileBasedIndexImpl.java:1055)
	at com.intellij.psi.stubs.StubIndexImpl$StubIdListContainerAction.<init>(StubIndexImpl.java:609)
	at com.intellij.psi.stubs.StubIndexImpl$2.<init>(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndexImpl.processElements(StubIndexImpl.java:323)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:145)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:134)
	at com.intellij.psi.impl.java.stubs.index.JavaFullClassNameIndex.get(JavaFullClassNameIndex.java:48)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.doFindClasses(JavaFileManagerImpl.java:96)
	at com.intellij.psi.impl.file.impl.JavaFileManagerImpl.findClass(JavaFileManagerImpl.java:131)
	at com.intellij.psi.impl.PsiElementFinderImpl.findClass(PsiElementFinderImpl.java:54)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.doFindClass(JavaPsiFacadeImpl.java:131)
	at com.intellij.psi.impl.JavaPsiFacadeImpl.findClass(JavaPsiFacadeImpl.java:108)
	at org.jetbrains.plugins.groovy.lang.resolve.ImplicitImportsKt.processImplicitImports(implicitImports.kt:82)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl.processDeclarationsNoGuess(GroovyFileImpl.java:228)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl.processDeclarations(GroovyFileImpl.java:144)
	at org.jetbrains.plugins.groovy.lang.psi.util.PsiTreeUtilKt.treeWalkUp(psiTreeUtil.kt:62)
	at org.jetbrains.plugins.groovy.lang.psi.util.PsiTreeUtilKt.treeWalkUp$default(psiTreeUtil.kt:60)
	at org.jetbrains.plugins.groovy.lang.psi.util.PsiTreeUtilKt.treeWalkUp(psiTreeUtil.kt)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver._resolve(GrCodeReferenceElementImpl.java:338)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver._resolve(GrCodeReferenceElementImpl.java:348)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:272)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:266)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl.multiResolve(GrCodeReferenceElementImpl.java:488)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.advancedResolve(GrReferenceElement.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.resolve(GrReferenceElement.java:38)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver._resolve(GrCodeReferenceElementImpl.java:327)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver._resolve(GrCodeReferenceElementImpl.java:348)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:272)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:266)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl.multiResolve(GrCodeReferenceElementImpl.java:488)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.advancedResolve(GrReferenceElement.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.resolve(GrReferenceElement.java:38)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver._resolve(GrCodeReferenceElementImpl.java:327)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:272)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:266)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl.multiResolve(GrCodeReferenceElementImpl.java:488)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.advancedResolve(GrReferenceElement.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.resolve(GrReferenceElement.java:38)
	at org.jetbrains.plugins.groovy.lang.psi.impl.toplevel.imports.GrImportStatementImpl.processSingleClassImport(GrImportStatementImpl.java:190)
	at org.jetbrains.plugins.groovy.lang.psi.impl.toplevel.imports.GrImportStatementImpl.processDeclarationsForSingleElement(GrImportStatementImpl.java:117)
	at org.jetbrains.plugins.groovy.lang.psi.impl.toplevel.imports.GrImportStatementImpl.processDeclarations(GrImportStatementImpl.java:89)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyImportHelper.processImports(GroovyImportHelper.java:91)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl.processImports(GroovyFileImpl.java:274)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl.processDeclarationsNoGuess(GroovyFileImpl.java:225)
	at org.jetbrains.plugins.groovy.lang.psi.impl.GroovyFileImpl.processDeclarations(GroovyFileImpl.java:144)
	at org.jetbrains.plugins.groovy.lang.psi.util.PsiTreeUtilKt.treeWalkUp(psiTreeUtil.kt:62)
	at org.jetbrains.plugins.groovy.lang.psi.util.PsiTreeUtilKt.treeWalkUp$default(psiTreeUtil.kt:60)
	at org.jetbrains.plugins.groovy.lang.psi.util.PsiTreeUtilKt.treeWalkUp(psiTreeUtil.kt)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver._resolve(GrCodeReferenceElementImpl.java:338)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:272)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl$OurResolver.resolve(GrCodeReferenceElementImpl.java:266)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$0(ResolveCache.java:142)
	at com.intellij.openapi.util.RecursionManager$2.doPreventingRecursion(RecursionManager.java:113)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:141)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:166)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:158)
	at org.jetbrains.plugins.groovy.lang.psi.impl.InferenceContext$1.multiResolve(InferenceContext.java:65)
	at org.jetbrains.plugins.groovy.lang.psi.impl.types.GrCodeReferenceElementImpl.multiResolve(GrCodeReferenceElementImpl.java:488)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.advancedResolve(GrReferenceElement.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.GrReferenceElement.resolve(GrReferenceElement.java:38)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrAnnotationCollector.findAnnotationCollector(GrAnnotationCollector.java:200)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrAnnotationCollector.hasAliases(GrAnnotationCollector.java:62)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrAnnotationCollector.getResolvedAnnotations(GrAnnotationCollector.java:43)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListImpl.lambda$getAnnotations$1(GrModifierListImpl.java:282)
	at com.intellij.psi.util.CachedValuesManager.lambda$getCachedValue$0(CachedValuesManager.java:140)
	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:49)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:38)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:136)
	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:126)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListImpl.getAnnotations(GrModifierListImpl.java:281)
	at org.jetbrains.plugins.groovy.lang.psi.impl.auxiliary.modifiers.GrModifierListImpl.getAnnotations(GrModifierListImpl.java:55)
	at com.intellij.codeInsight.AnnotationUtil$1.create(AnnotationUtil.java:98)
	at com.intellij.codeInsight.AnnotationUtil$1.create(AnnotationUtil.java:92)
	at com.intellij.util.containers.FactoryMap.get(FactoryMap.java:58)
	at com.intellij.codeInsight.AnnotationUtil.findOwnAnnotation(AnnotationUtil.java:108)
	at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:81)
	at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:64)
	at com.intellij.codeInsight.AnnotationUtil.findAnnotation(AnnotationUtil.java:57)
	at com.intellij.psi.impl.PsiImplUtil.isDeprecatedByAnnotation(PsiImplUtil.java:457)
	at org.jetbrains.plugins.groovy.lang.psi.impl.statements.typedef.GrTypeDefinitionImpl.isDeprecated(GrTypeDefinitionImpl.java:536)
	at com.intellij.ide.projectView.impl.nodes.BasePsiMemberNode.isDeprecated(BasePsiMemberNode.java:44)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.a(AbstractPsiBasedNode.java:158)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:933)
	at com.intellij.ide.projectView.impl.nodes.AbstractPsiBasedNode.update(AbstractPsiBasedNode.java:139)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.getUpdatedPresentation(PresentableNodeDescriptor.java:88)
	at com.intellij.ide.util.treeView.PresentableNodeDescriptor.update(PresentableNodeDescriptor.java:41)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.updateNodeDescriptor(AbstractTreeBuilder.java:577)
	at com.intellij.ide.util.treeView.AbstractTreeUi$22.perform(AbstractTreeUi.java:935)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1856)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:931)
	at com.intellij.ide.util.treeView.AbstractTreeUi.update(AbstractTreeUi.java:883)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3004)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$4900(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32$1.run(AbstractTreeUi.java:1718)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1835)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5200(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33.perform(AbstractTreeUi.java:1801)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2090)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5800(AbstractTreeUi.java:64)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36$1.perform(AbstractTreeUi.java:2002)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:433)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2185)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36.perform(AbstractTreeUi.java:1997)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.lambda$new$0(AbstractTreeBuilder.java:51)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:102)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:57)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.g(IdeEventQueue.java:821)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:649)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:365)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

1. Update to .ignore 2.2.0
2. Restart IntelliJ
3. Observe error

**Expected behavior:** No errors.

**Actual behavior:** Error message seen above.

**Reproduces how often:** Only once so far. Subsequent restarts did not produce error.

### Versions

**Plugin:**
2.2.0

**IDE:** 
IntelliJ IDEA 2017.2.3
Build #IU-172.3968.16, built on August 21, 2017
JRE: 1.8.0_152-release-915-b11 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**OS:** 
Mac OS X 10.12.6

**Comment by hsz** [comment]
I have just published `v2.2.1-RC1` which is available in [Early Access Preview repository channel](https://github.com/hsz/idea-gitignore#early-access-preview-repository-channel) or for [manual installation](https://github.com/hsz/idea-gitignore/releases/tag/v2.2.1-RC1)

Can you please check if this issue is resolved for you?
