### ISSUE TITLE
version 2.2.2 is not working with IntelliJ IDEA 2017.3 EAP Public Preview

### ISSUE THREAD

**Issue by dejan2609** [hsz/idea-gitignore#491]
* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description
Plugin version **2.2.2** is not working with IntelliJ IDEA 2017.3 EAP Public Preview (Build #IC-173.3415.22, built on October 25, 2017)

```
26-Oct-17
15:52	Plugin Error
			Problems found loading plugins:
			The following plugins are incompatible with the current IDE build: .ignore

```

### Stack trace

```
2017-10-25 10:48:22,239 [ 144757]   INFO - notification.NotificationGroup - Notification group IGNORE_GROUP is already registered 
java.lang.Throwable
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:65)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:50)
	at com.intellij.notification.NotificationGroup.<init>(NotificationGroup.java:43)
	at mobi.hsz.idea.gitignore.util.Notify.show(Notify.java:84)
	at mobi.hsz.idea.gitignore.util.Notify.show(Notify.java:68)
	at mobi.hsz.idea.gitignore.TrackedIgnoredFilesComponent.handleFiles(TrackedIgnoredFilesComponent.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:448)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:409)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:398)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:386)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:379)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy122.handleFiles(Unknown Source)
	at mobi.hsz.idea.gitignore.IgnoreManager$RefreshTrackedIgnoredRunnable.run(IgnoreManager.java:601)
	at mobi.hsz.idea.gitignore.IgnoreManager$RefreshTrackedIgnoredRunnable.run(IgnoreManager.java:567)
	at mobi.hsz.idea.gitignore.IgnoreManager$5.task(IgnoreManager.java:180)
	at mobi.hsz.idea.gitignore.IgnoreManager$5.task(IgnoreManager.java:174)
	at mobi.hsz.idea.gitignore.util.Debounced$1.run(Debounced.java:72)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:242)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2017-10-25 10:48:30,904 [ 153422]   INFO - .diagnostic.PerformanceWatcher - Unindexed files update took 19694ms; general responsiveness: ok; EDT responsiveness: 0/20 sluggish, 1/20 very slow 

```

### Steps to Reproduce
1. upgrade to IntelliJ IDEA 2017.3 EAP Public Preview (Build #IC-173.3415.22, built on October 25, 2017)

### Versions

**Plugin:** 

```
2.2.2
```

**IDE:** 

```
			
IntelliJ IDEA 2017.3 EAP (Community Edition)
Build #IC-173.3415.22, built on October 25, 2017
JRE: 1.8.0_144-b01 amd64
JVM: Java HotSpot(TM) 64-Bit Server VM by Oracle Corporation
Windows 10 10.0

```

**OS:** 

```
Windows 10, 64 bit, version 1709
```

**Comment by Scott-G** [comment]
Also seeing this in: 
PhpStorm 2017.3 EAP
Build #PS-173.3415.21, built on October 25, 2017
PhpStorm EAP User
Expiration date: November 24, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
.ignore Version: 2.2.2

**Comment by arnemertz** [comment]
Same in new CLion 2017.3 EAP build
Build #CL-173.3415.24, built on October 25, 2017
JRE: 1.8.0_152-release-1024-b6 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 8.1 6.3

**Comment by dejan2609** [comment]
Just to be more precise: IntelliJ upgrade **_from_** 2017.3 EAP 173.3302.5 (Released: October 18, 2017) **_to_** 2017.3 Public Preview 173.3415.22 (Released: October 26, 2017) introduced some issues for *idea-gitignore* plugin version *2.2.2*

Related links:
- https://blog.jetbrains.com/idea/2017/10/intellij-idea-2017-3-public-preview/
- https://confluence.jetbrains.com/display/IDEADEV/IntelliJ+IDEA+2017.3+173.3415.22+Release+Notes

@hsz I can try to perform git bisect in order to discover **intellij-community** exact commit that caused issues for your plugin. Sounds good ?

**Comment by hsz** [comment]
@dejan2609  thank you for this report. Since we have many thumbs up, I'll fix it for sure this weekend and release - so I'd open this issue back.

I know what is the issue, commit discovering is not required, but thank you very much!

**Comment by dejan2609** [comment]
Note: just realized that I accidentally closed this ticket...

@hsz take your time and thanx in advance !

**Comment by drorventura** [comment]
same with:
Gogland (1.0 Preview) 1.0 EAP
Build #GO-173.3415.23, built on October 25, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

.ignore Version: 2.2.1

**Comment by justinlynn** [comment]
Looks like `mobi.hsz.idea.gitignore` <= 2.2.2 was added to the brokenPlugins.txt resource in resources.jar for the latest IntelliJ release. Should reach out to Jetbrains to figure out why they've blocked the plugin again as in #408

**Comment by hsz** [comment]
Fix has been released with `v2.3.0-RC.1` on EAP channel. Can you please verify if everything is fine for you?

**Comment by mehrentreich** [comment]
@hsz For me your plugin works again as expected. Thanks a lot!

IntelliJ IDEA 2017.3 EAP (Ultimate Edition)
Build #IU-173.3415.22, built on October 25, 2017
IntelliJ IDEA EAP User
Expiration date: November 24, 2017
JRE: 1.8.0_144-b01 amd64
JVM: OpenJDK 64-Bit Server VM by Azul Systems, Inc.
Linux 4.4.0-62-generic

**Comment by philCryoport** [comment]
I'm using PHPStorm EAP 2017.3 and it still thinks the latest .ignore plugin is v2.2.2

**Comment by hsz** [comment]
@philCryoport 

This early build is not available in public plugin channel. 
Here is the instruction for switching to [Early Access Preview repository channel](https://github.com/hsz/idea-gitignore/#early-access-preview-repository-channel)

You an also download it manually from [releases section](https://github.com/hsz/idea-gitignore/releases)

**Comment by Scott-G** [comment]
EAP v2.3.0-RC.1 has everything working fine for me again. Thanks.

**Comment by dejan2609** [comment]
Plugin version `2.3.0-RC.1` works like a charm with IntelliJ IDEA 2017.3 EAP (Build #IC-173.3415.22).
Thanx @hsz !

**Comment by nicity** [comment]
Previous plugin versions affects IDE stability and performance: 
- https://youtrack.jetbrains.com/issue/IDEA-180296
- https://youtrack.jetbrains.com/issue/IDEA-180954
Here are comment for plugin's author in advance 
- https://github.com/hsz/idea-gitignore/issues/484#issuecomment-337858100
- https://youtrack.jetbrains.com/issue/IDEA-180954#comment=27-2492220

**Comment by hsz** [comment]
@nicity I have reviewed above issues and everything should be now fine. All of your suggestions have been applied.

**Comment by nicity** [comment]
Thank you for fixing the issues!
My comment is about (historical) reasoning of the particular version having been disabled and notifications to you currently being used.

**Comment by hsz** [comment]
Yeah, it's also a good summary for this thread.
I'll handle a couple more things this week and then go with me public rise. Until then it'll be available only in EAP channel.

**Comment by boxsters1423** [comment]
I can not start IntelliJ anymore after updating gitignore plugin. Preparing workspace... and nothing comes.
![banners_and_alerts_et__gitignore_-_cari_-____gitroot_cari_](https://user-images.githubusercontent.com/33317024/32322317-6a918d5e-bfc4-11e7-9883-a07b98f44c52.png)

**Comment by hsz** [comment]
@boxsters1423 Thanks for letting me know. This is very strange situation.

Do you have any logs? I.e. when starting IDE from command line.
Do other projects are loading correctly?

**Comment by boxsters1423** [comment]
macOs Sierra 10.12.6 (16G29)
IntelliJ IDEA 2017.2.5 Ultimate
@hsz How can I start it from command line ? show logs ? and remove the plugin ?

**Comment by hsz** [comment]
@boxsters1423 On Mac OS logs and plugins should be located in:

> Logs (idea.log.path):
> ~/Library/Logs/<PRODUCT><VERSION>
> Plugins (idea.plugins.path):
> ~/Library/Application Support/<PRODUCT><VERSION>

**Comment by boxsters1423** [comment]
@hsz I updated to the new IntelliJ release 2017.2.5 perhaps it will work.

**Comment by dejan2609** [comment]
@hsz I guess this ticket can be closed: 
* two weeks passed since last comment was submitted and 
* plugin version **2.2.2** is working as expected on IDEA 2017.3 **(Build #IC-173.3622.25, built on November 9, 2017).**

**Comment by hsz** [comment]
@boxsters1423 @dejan2609 Thanks for the confirmation! Closing.

**Comment by EnisGusinac** [comment]
Im having the same problem:
I have moved from 2017.2.3 to the the new InteliJ 2017.3 version, and now cannot make any commits and pull requests on my Company app repository (they are still using 2017.2.3 version).
Any advice?
