### ISSUE TITLE
Plugin crash when using Rider

### ISSUE THREAD

**Issue by walterdolce** [hsz/idea-gitignore#522]
### Prerequisites

* [x] Plugin is in the latest version
* [x] Issue was not reported yet
* [x] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

When I open a `.gitignore` file, the plugin crashes. Note I removed the absoute path to the project with `{{path_to_my_project}}`.

```
Catch: Not initialized: SolutionModel.solutions.[1].editors.documents.[EditableEntityId(projectModelElementId=0, filePath={{path_to_my_project}}/.git/info/exclude)].markup
java.lang.IllegalStateException: Not initialized: SolutionModel.solutions.[1].editors.documents.[EditableEntityId(projectModelElementId=0, filePath={{path_to_my_project}}/.git/info/exclude)].markup
	at com.jetbrains.rider.util.reactive.Property$value$1.invoke(Property.kt:24)
	at com.jetbrains.rider.util.reactive.Property$value$1.invoke(Property.kt:7)
	at com.jetbrains.rider.util.Maybe.orElseThrow(Monad.kt:29)
	at com.jetbrains.rider.util.reactive.Property.getValue(Property.kt:24)
	at com.jetbrains.rider.framework.impl.RdProperty.getValue(RdProperty.kt:112)
	at com.jetbrains.rider.daemon.components.RiderDaemonHost$2.invoke(RiderDaemonHost.kt:73)
	at com.jetbrains.rider.daemon.components.RiderDaemonHost$2.invoke(RiderDaemonHost.kt:29)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:165)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:124)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:144)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:124)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:156)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:124)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:29)
	at com.jetbrains.rider.util.reactive.ViewableMap.put(ViewableMap.kt:33)
	at com.jetbrains.rider.editors.TextControlHost.a(TextControlHost.kt:174)
	at com.jetbrains.rider.editors.TextControlHost.access$subscribeForEditor(TextControlHost.kt:52)
	at com.jetbrains.rider.editors.TextControlHost$1$1.invoke(TextControlHost.kt:102)
	at com.jetbrains.rider.editors.TextControlHost$1$1.invoke(TextControlHost.kt:52)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:165)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$2.invoke(Interfaces.kt:124)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:144)
	at com.jetbrains.rider.util.reactive.IViewableMap$view$1.invoke(Interfaces.kt:124)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:156)
	at com.jetbrains.rider.util.reactive.IViewableMap$adviseAddRemove$1.invoke(Interfaces.kt:124)
	at com.jetbrains.rider.util.reactive.Signal.fire(Signal.kt:29)
	at com.jetbrains.rider.util.reactive.ViewableMap.put(ViewableMap.kt:33)
	at com.jetbrains.rider.framework.impl.RdMap$put$1.invoke(RdMap.kt:163)
	at com.jetbrains.rider.framework.base.RdReactiveBase.localChange(RdReactiveBase.kt:45)
	at com.jetbrains.rider.framework.impl.RdMap.put(RdMap.kt:163)
	at com.jetbrains.rider.editors.TextControlHost.a(TextControlHost.kt:747)
	at com.jetbrains.rider.editors.TextControlHost.bindEditor$rider(TextControlHost.kt:297)
	at com.jetbrains.rider.editors.TextControlHost.editorCreated(TextControlHost.kt:236)
	at sun.reflect.GeneratedMethodAccessor124.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.EventDispatcher.dispatch(EventDispatcher.java:99)
	at com.intellij.util.EventDispatcher.access$200(EventDispatcher.java:35)
	at com.intellij.util.EventDispatcher$2.invoke(EventDispatcher.java:79)
	at com.sun.proxy.$Proxy37.editorCreated(Unknown Source)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.a(EditorFactoryImpl.java:223)
	at com.intellij.openapi.editor.impl.EditorFactoryImpl.createEditor(EditorFactoryImpl.java:195)
	at mobi.hsz.idea.gitignore.util.Utils.createPreviewEditor(Utils.java:370)
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreWrapper.<init>(OuterIgnoreWrapper.java:121)
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreLoaderComponent$IgnoreEditorManagerListener$1.run(OuterIgnoreLoaderComponent.java:131)
	at com.intellij.openapi.project.DumbServiceImpl.lambda$runWhenSmart$0(DumbServiceImpl.java:170)
	at com.intellij.ide.startup.impl.StartupManagerImpl.lambda$runWhenProjectIsInitialized$5(StartupManagerImpl.java:396)
	at com.intellij.ui.GuiUtils.invokeLaterIfNeeded(GuiUtils.java:377)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runWhenProjectIsInitialized(StartupManagerImpl.java:398)
	at com.intellij.openapi.project.DumbServiceImpl.runWhenSmart(DumbServiceImpl.java:162)
	at mobi.hsz.idea.gitignore.outer.OuterIgnoreLoaderComponent$IgnoreEditorManagerListener.fileOpened(OuterIgnoreLoaderComponent.java:120)
	at sun.reflect.GeneratedMethodAccessor118.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:449)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:410)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:399)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:387)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:380)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:45)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:231)
	at com.sun.proxy.$Proxy123.fileOpened(Unknown Source)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$null$7(FileEditorManagerImpl.java:938)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$5$1.run(FileEditorManagerImpl.java:1031)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:640)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$15(FocusManagerImpl.java:491)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.a(FocusManagerImpl.java:643)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.p(FocusManagerImpl.java:624)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.f(FocusManagerImpl.java:594)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$doWhenFocusSettlesDown$13(FocusManagerImpl.java:476)
	at com.intellij.util.ui.UIUtil.invokeLaterIfNeeded(UIUtil.java:2760)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:456)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.doWhenFocusSettlesDown(FocusManagerImpl.java:489)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.lambda$null$14(FocusManagerImpl.java:495)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:315)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.a(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:822)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:650)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:366)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

1. Open a `.gitignore` file.

**Expected behavior:** The plugin should not crash.

**Actual behavior:** The plugin generates an error and Rider shows me the popup with the stack trace.

**Reproduces how often:** Every time I open a `.gitignore` file.

### Versions

**Plugin:** 

2.4.0

**IDE:** 

<img width="472" alt="screen shot 2018-03-05 at 17 20 08" src="https://user-images.githubusercontent.com/6195629/36989402-8a1890f6-2099-11e8-923a-6fa61e598f17.png">
<img width="471" alt="screen shot 2018-03-05 at 17 20 21" src="https://user-images.githubusercontent.com/6195629/36989403-8a3479a6-2099-11e8-91f9-24902a26af2f.png">

**OS:** 

macOS High Sierra 10.13.3

**Comment by hsz** [comment]
@walterdolce Thank you for this report. It's not said directly (different exception message), but comparing the stacktraces, this issue looks equal to the #385 
I have fixed it just a few minutes ago (here is a wider explanation of this issue: https://github.com/hsz/idea-gitignore/issues/385#issuecomment-375918876)

Fix will be released next week with `v2.5.0`.
