### ISSUE TITLE
IDE Fatal Error on start: Argument for @NotNull parameter 'settings' of mobi/hsz/idea/gitignore/projectView/HideIgnoredFilesTreeStructureProvider.modify must not be null

### ISSUE THREAD

**Issue by hsandt** [hsz/idea-gitignore#551]
### Prerequisites

* [X] Plugin is in the latest version
* [X] Issue was not reported yet
* [X] Stack trace (if provided) contains `mobi.hsz.idea.gitignore` package name

### Description

_IDE Fatal Error occurs on start (of a project with a .gitignore): Argument for @NotNull parameter 'settings' of mobi/hsz/idea/gitignore/projectView/HideIgnoredFilesTreeStructureProvider.modify must not be null_

```
Argument for @NotNull parameter 'settings' of mobi/hsz/idea/gitignore/projectView/HideIgnoredFilesTreeStructureProvider.modify must not be null
java.lang.IllegalArgumentException: Argument for @NotNull parameter 'settings' of mobi/hsz/idea/gitignore/projectView/HideIgnoredFilesTreeStructureProvider.modify must not be null
	at mobi.hsz.idea.gitignore.projectView.HideIgnoredFilesTreeStructureProvider.$$$reportNull$$$0(HideIgnoredFilesTreeStructureProvider.java)
	at mobi.hsz.idea.gitignore.projectView.HideIgnoredFilesTreeStructureProvider.modify(HideIgnoredFilesTreeStructureProvider.java)
	at com.intellij.ide.util.treeView.AbstractTreeStructureBase.getChildElements(AbstractTreeStructureBase.java:40)
	at com.intellij.ide.util.treeView.AbstractTreeUi$31.perform(AbstractTreeUi.java:1609)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1846)
	at com.intellij.ide.util.treeView.AbstractTreeUi.getChildrenFor(AbstractTreeUi.java:1606)
	at com.intellij.ide.util.treeView.AbstractTreeUi.loadElementsFromStructure(AbstractTreeUi.java:2196)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildrenNow(AbstractTreeUi.java:1349)
	at com.intellij.ide.util.treeView.AbstractTreeUi.doUpdateChildren(AbstractTreeUi.java:1271)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$3000(AbstractTreeUi.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUi$25$1.perform(AbstractTreeUi.java:1163)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1846)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2600(AbstractTreeUi.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUi$25.perform(AbstractTreeUi.java:1160)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.openapi.util.ActionCallback$ExecutedExecutionCallback.doWhenExecuted(ActionCallback.java:177)
	at com.intellij.openapi.util.ActionCallback.doWhenDone(ActionCallback.java:111)
	at com.intellij.ide.util.treeView.AbstractTreeUi.updateNodeChildren(AbstractTreeUi.java:1155)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$2200(AbstractTreeUi.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUi$49.perform(AbstractTreeUi.java:3099)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.TreeRunnable$TreeConsumer.consume(TreeRunnable.java:50)
	at org.jetbrains.concurrency.AsyncPromise.setHandler(AsyncPromise.kt:201)
	at org.jetbrains.concurrency.AsyncPromise.done(AsyncPromise.kt:43)
	at com.intellij.ide.util.treeView.AbstractTreeUi.lambda$processExistingNode$7(AbstractTreeUi.java:3059)
	at org.jetbrains.concurrency.AsyncPromise.setHandler(AsyncPromise.kt:201)
	at org.jetbrains.concurrency.AsyncPromise.done(AsyncPromise.kt:43)
	at com.intellij.ide.util.treeView.AbstractTreeUi.processExistingNode(AbstractTreeUi.java:3003)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5000(AbstractTreeUi.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUi$32$1.run(AbstractTreeUi.java:1708)
	at com.intellij.ide.util.treeView.AbstractTreeUi.execute(AbstractTreeUi.java:1825)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5300(AbstractTreeUi.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUi$33.perform(AbstractTreeUi.java:1791)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeUi.executeYieldingRequest(AbstractTreeUi.java:2080)
	at com.intellij.ide.util.treeView.AbstractTreeUi.access$5900(AbstractTreeUi.java:49)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36$1.perform(AbstractTreeUi.java:1992)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.runOnYeildingDone(AbstractTreeBuilder.java:411)
	at com.intellij.ide.util.treeView.AbstractTreeUi.runOnYieldingDone(AbstractTreeUi.java:2175)
	at com.intellij.ide.util.treeView.AbstractTreeUi$36.perform(AbstractTreeUi.java:1987)
	at com.intellij.ide.util.treeView.TreeRunnable.run(TreeRunnable.java:36)
	at com.intellij.ide.util.treeView.AbstractTreeBuilder.lambda$new$0(AbstractTreeBuilder.java:50)
	at com.intellij.util.containers.TransferToEDTQueue.processNext(TransferToEDTQueue.java:120)
	at com.intellij.util.containers.TransferToEDTQueue.access$300(TransferToEDTQueue.java:37)
	at com.intellij.util.containers.TransferToEDTQueue$1.run(TransferToEDTQueue.java:67)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.q(IdeEventQueue.java:786)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:727)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:395)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

Just started the project and let .ignore analyze it. It has a normal .gitignore file in which I've just added Jetbrains files to ignore.
Note that the error didn't occur with the previous version of the plugin. As I upgraded to both Rider 2018.1.2 and .ignore's last version, I got the exception.

**Expected behavior:** _What you expect to happen_

**Actual behavior:** _What actually happens_

**Reproduces how often:** _100%. Besides, the exception occurs again and again as the popup is open (you can see the counter incrementing: 4, 5, 6, 7...)_

### Versions

**Plugin:** 

```
2.6.2
```

**IDE:** 

```
JetBrains Rider 2018.1.2
Build #RD-181.4952.297, built on May 30, 2018
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**OS:** 

```
Linux 4.4.0-122-generic
Ubuntu 16.04
```

### Additional Information

_None_

**Comment by hsz** [comment]
Thanks for this report, fix will be released with `v2.6.3`.
