### ISSUE TITLE
Save settings failed 

### ISSUE THREAD

**Issue by abysKri** [hsz/idea-gitignore#552]
### Prerequisites
[*] Plugin is in the latest version

### Description
By installing the plugin, when i want to save files, the error "Save settings failed" appear
The Plugin popup always open on startup

```
2018-06-29 12:01:20,337 [  47428]   WARN - mponents.impl.stores.StoreUtil - Save settings failed 
java.lang.StringIndexOutOfBoundsException: String index out of range: 0
	at java.lang.String.charAt(String.java:658)
	at com.intellij.configurationStore.ApplicationStorageManager.expandMacros(ApplicationStoreImpl.kt:108)
	at com.intellij.configurationStore.StateStorageManagerImpl.createStateStorage(StateStorageManagerImpl.kt:194)
	at com.intellij.configurationStore.StateStorageManagerImpl.getOrCreateStorage(StateStorageManagerImpl.kt:150)
	at com.intellij.configurationStore.StateStorageManagerImpl.getStateStorage(StateStorageManagerImpl.kt:133)
	at com.intellij.configurationStore.StateStorageManagerImpl$startExternalization$1.setState(StateStorageManagerImpl.kt:342)
	at com.intellij.configurationStore.ComponentStoreImpl.a(ComponentStoreImpl.kt:199)
	at com.intellij.configurationStore.ComponentStoreImpl.save(ComponentStoreImpl.kt:124)
	at com.intellij.openapi.components.impl.stores.StoreUtil.save(StoreUtil.java:49)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveSettings(ApplicationImpl.java:1433)
	at com.intellij.openapi.application.impl.ApplicationImpl.saveAll(ApplicationImpl.java:1452)
	at com.intellij.ide.actions.SaveAllAction.actionPerformed(SaveAllAction.java:27)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher$3.performAction(IdeKeyEventDispatcher.java:595)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.processAction(IdeKeyEventDispatcher.java:646)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.a(IdeKeyEventDispatcher.java:485)
	at com.intellij.openapi.keymap.impl.IdeKeyEventDispatcher.dispatchKeyEvent(IdeKeyEventDispatcher.java:215)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:622)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:381)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### Steps to Reproduce

1. Install plugin
2. Restart PhpStorm
3. Change & save a file

### Versions

**Plugin:** 
.gitignore v 2.6.2

**IDE:** 
PHPStorm V 10.0.4
Build PS 143.2370

**OS:** 
Windows 10
Version 1803 - 17134.112

**Comment by hsz** [comment]
@abysKri Thanks for the report, but it doesn't seems to be related to the plugin.
